<?php
/**
 * CandyDropV4PrizePoolCd03
 *
 * PHP version 7
 *
 * @category Class
 * @package  GateApi
 * @author   Gate
 * @link     https://www.gate.com
 */

/**
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: https://openapi-generator.tech
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */

namespace GateApi\Model;

use \ArrayAccess;
use \GateApi\ObjectSerializer;

/**
 * CandyDropV4PrizePoolCd03 Class Doc Comment
 *
 * @category Class
 * @package  GateApi
 * @author   Gate
 * @link     https://www.gate.com
 */
class CandyDropV4PrizePoolCd03 implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'CandyDropV4PrizePool_cd03';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'prize_pool_type' => 'int',
        'prize_all' => 'string',
        'prize_limit' => 'string',
        'tasks' => '\GateApi\Model\CandyDropV4TaskCd03[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPIFormats = [
        'prize_pool_type' => null,
        'prize_all' => null,
        'prize_limit' => null,
        'tasks' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'prize_pool_type' => 'prize_pool_type',
        'prize_all' => 'prize_all',
        'prize_limit' => 'prize_limit',
        'tasks' => 'tasks'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'prize_pool_type' => 'setPrizePoolType',
        'prize_all' => 'setPrizeAll',
        'prize_limit' => 'setPrizeLimit',
        'tasks' => 'setTasks'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'prize_pool_type' => 'getPrizePoolType',
        'prize_all' => 'getPrizeAll',
        'prize_limit' => 'getPrizeLimit',
        'tasks' => 'getTasks'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['prize_pool_type'] = isset($data['prize_pool_type']) ? $data['prize_pool_type'] : null;
        $this->container['prize_all'] = isset($data['prize_all']) ? $data['prize_all'] : null;
        $this->container['prize_limit'] = isset($data['prize_limit']) ? $data['prize_limit'] : null;
        $this->container['tasks'] = isset($data['tasks']) ? $data['tasks'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets prize_pool_type
     *
     * @return int|null
     */
    public function getPrizePoolType()
    {
        return $this->container['prize_pool_type'];
    }

    /**
     * Sets prize_pool_type
     *
     * @param int|null $prize_pool_type 奖池类型
     *
     * @return $this
     */
    public function setPrizePoolType($prize_pool_type)
    {
        $this->container['prize_pool_type'] = $prize_pool_type;

        return $this;
    }

    /**
     * Gets prize_all
     *
     * @return string|null
     */
    public function getPrizeAll()
    {
        return $this->container['prize_all'];
    }

    /**
     * Sets prize_all
     *
     * @param string|null $prize_all 奖池总额度
     *
     * @return $this
     */
    public function setPrizeAll($prize_all)
    {
        $this->container['prize_all'] = $prize_all;

        return $this;
    }

    /**
     * Gets prize_limit
     *
     * @return string|null
     */
    public function getPrizeLimit()
    {
        return $this->container['prize_limit'];
    }

    /**
     * Sets prize_limit
     *
     * @param string|null $prize_limit 每人瓜分上限
     *
     * @return $this
     */
    public function setPrizeLimit($prize_limit)
    {
        $this->container['prize_limit'] = $prize_limit;

        return $this;
    }

    /**
     * Gets tasks
     *
     * @return \GateApi\Model\CandyDropV4TaskCd03[]|null
     */
    public function getTasks()
    {
        return $this->container['tasks'];
    }

    /**
     * Sets tasks
     *
     * @param \GateApi\Model\CandyDropV4TaskCd03[]|null $tasks 任务列表
     *
     * @return $this
     */
    public function setTasks($tasks)
    {
        $this->container['tasks'] = $tasks;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


