<?php
/**
 * ContractDetailDataList
 *
 * PHP version 7
 *
 * @category Class
 * @package  GateApi
 * @author   Gate
 * @link     https://www.gate.com
 */

/**
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: https://openapi-generator.tech
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */

namespace GateApi\Model;

use \ArrayAccess;
use \GateApi\ObjectSerializer;

/**
 * ContractDetailDataList Class Doc Comment
 *
 * @category Class
 * @description Futures contract details
 * @package  GateApi
 * @author   Gate
 * @link     https://www.gate.com
 */
class ContractDetailDataList implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ContractDetail_data_list';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'symbol' => 'string',
        'symbol_desc' => 'string',
        'category_name' => 'string',
        'contract_volume' => 'string',
        'settlement_currency' => 'string',
        'max_order_volume' => 'string',
        'min_order_volume' => 'string',
        'leverage' => 'string',
        'price_precision' => 'int',
        'price_sl_level' => 'string',
        'swap_cost_type' => 'string',
        'buy_swap_cost_rate' => 'string',
        'sell_swap_cost_rate' => 'string',
        'swap_cost_3day' => 'string',
        'trade_timezone' => 'string',
        'trade_mode' => 'string',
        'icon_link' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPIFormats = [
        'symbol' => null,
        'symbol_desc' => null,
        'category_name' => null,
        'contract_volume' => null,
        'settlement_currency' => null,
        'max_order_volume' => null,
        'min_order_volume' => null,
        'leverage' => null,
        'price_precision' => null,
        'price_sl_level' => null,
        'swap_cost_type' => null,
        'buy_swap_cost_rate' => null,
        'sell_swap_cost_rate' => null,
        'swap_cost_3day' => null,
        'trade_timezone' => null,
        'trade_mode' => null,
        'icon_link' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'symbol' => 'symbol',
        'symbol_desc' => 'symbol_desc',
        'category_name' => 'category_name',
        'contract_volume' => 'contract_volume',
        'settlement_currency' => 'settlement_currency',
        'max_order_volume' => 'max_order_volume',
        'min_order_volume' => 'min_order_volume',
        'leverage' => 'leverage',
        'price_precision' => 'price_precision',
        'price_sl_level' => 'price_sl_level',
        'swap_cost_type' => 'swap_cost_type',
        'buy_swap_cost_rate' => 'buy_swap_cost_rate',
        'sell_swap_cost_rate' => 'sell_swap_cost_rate',
        'swap_cost_3day' => 'swap_cost_3day',
        'trade_timezone' => 'trade_timezone',
        'trade_mode' => 'trade_mode',
        'icon_link' => 'icon_link'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'symbol' => 'setSymbol',
        'symbol_desc' => 'setSymbolDesc',
        'category_name' => 'setCategoryName',
        'contract_volume' => 'setContractVolume',
        'settlement_currency' => 'setSettlementCurrency',
        'max_order_volume' => 'setMaxOrderVolume',
        'min_order_volume' => 'setMinOrderVolume',
        'leverage' => 'setLeverage',
        'price_precision' => 'setPricePrecision',
        'price_sl_level' => 'setPriceSlLevel',
        'swap_cost_type' => 'setSwapCostType',
        'buy_swap_cost_rate' => 'setBuySwapCostRate',
        'sell_swap_cost_rate' => 'setSellSwapCostRate',
        'swap_cost_3day' => 'setSwapCost3day',
        'trade_timezone' => 'setTradeTimezone',
        'trade_mode' => 'setTradeMode',
        'icon_link' => 'setIconLink'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'symbol' => 'getSymbol',
        'symbol_desc' => 'getSymbolDesc',
        'category_name' => 'getCategoryName',
        'contract_volume' => 'getContractVolume',
        'settlement_currency' => 'getSettlementCurrency',
        'max_order_volume' => 'getMaxOrderVolume',
        'min_order_volume' => 'getMinOrderVolume',
        'leverage' => 'getLeverage',
        'price_precision' => 'getPricePrecision',
        'price_sl_level' => 'getPriceSlLevel',
        'swap_cost_type' => 'getSwapCostType',
        'buy_swap_cost_rate' => 'getBuySwapCostRate',
        'sell_swap_cost_rate' => 'getSellSwapCostRate',
        'swap_cost_3day' => 'getSwapCost3day',
        'trade_timezone' => 'getTradeTimezone',
        'trade_mode' => 'getTradeMode',
        'icon_link' => 'getIconLink'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['symbol'] = isset($data['symbol']) ? $data['symbol'] : null;
        $this->container['symbol_desc'] = isset($data['symbol_desc']) ? $data['symbol_desc'] : null;
        $this->container['category_name'] = isset($data['category_name']) ? $data['category_name'] : null;
        $this->container['contract_volume'] = isset($data['contract_volume']) ? $data['contract_volume'] : null;
        $this->container['settlement_currency'] = isset($data['settlement_currency']) ? $data['settlement_currency'] : null;
        $this->container['max_order_volume'] = isset($data['max_order_volume']) ? $data['max_order_volume'] : null;
        $this->container['min_order_volume'] = isset($data['min_order_volume']) ? $data['min_order_volume'] : null;
        $this->container['leverage'] = isset($data['leverage']) ? $data['leverage'] : null;
        $this->container['price_precision'] = isset($data['price_precision']) ? $data['price_precision'] : null;
        $this->container['price_sl_level'] = isset($data['price_sl_level']) ? $data['price_sl_level'] : null;
        $this->container['swap_cost_type'] = isset($data['swap_cost_type']) ? $data['swap_cost_type'] : null;
        $this->container['buy_swap_cost_rate'] = isset($data['buy_swap_cost_rate']) ? $data['buy_swap_cost_rate'] : null;
        $this->container['sell_swap_cost_rate'] = isset($data['sell_swap_cost_rate']) ? $data['sell_swap_cost_rate'] : null;
        $this->container['swap_cost_3day'] = isset($data['swap_cost_3day']) ? $data['swap_cost_3day'] : null;
        $this->container['trade_timezone'] = isset($data['trade_timezone']) ? $data['trade_timezone'] : null;
        $this->container['trade_mode'] = isset($data['trade_mode']) ? $data['trade_mode'] : null;
        $this->container['icon_link'] = isset($data['icon_link']) ? $data['icon_link'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets symbol
     *
     * @return string|null
     */
    public function getSymbol()
    {
        return $this->container['symbol'];
    }

    /**
     * Sets symbol
     *
     * @param string|null $symbol Trading symbol code
     *
     * @return $this
     */
    public function setSymbol($symbol)
    {
        $this->container['symbol'] = $symbol;

        return $this;
    }

    /**
     * Gets symbol_desc
     *
     * @return string|null
     */
    public function getSymbolDesc()
    {
        return $this->container['symbol_desc'];
    }

    /**
     * Sets symbol_desc
     *
     * @param string|null $symbol_desc Trading symbol description
     *
     * @return $this
     */
    public function setSymbolDesc($symbol_desc)
    {
        $this->container['symbol_desc'] = $symbol_desc;

        return $this;
    }

    /**
     * Gets category_name
     *
     * @return string|null
     */
    public function getCategoryName()
    {
        return $this->container['category_name'];
    }

    /**
     * Sets category_name
     *
     * @param string|null $category_name Category name
     *
     * @return $this
     */
    public function setCategoryName($category_name)
    {
        $this->container['category_name'] = $category_name;

        return $this;
    }

    /**
     * Gets contract_volume
     *
     * @return string|null
     */
    public function getContractVolume()
    {
        return $this->container['contract_volume'];
    }

    /**
     * Sets contract_volume
     *
     * @param string|null $contract_volume Contract Volume
     *
     * @return $this
     */
    public function setContractVolume($contract_volume)
    {
        $this->container['contract_volume'] = $contract_volume;

        return $this;
    }

    /**
     * Gets settlement_currency
     *
     * @return string|null
     */
    public function getSettlementCurrency()
    {
        return $this->container['settlement_currency'];
    }

    /**
     * Sets settlement_currency
     *
     * @param string|null $settlement_currency Settle currency
     *
     * @return $this
     */
    public function setSettlementCurrency($settlement_currency)
    {
        $this->container['settlement_currency'] = $settlement_currency;

        return $this;
    }

    /**
     * Gets max_order_volume
     *
     * @return string|null
     */
    public function getMaxOrderVolume()
    {
        return $this->container['max_order_volume'];
    }

    /**
     * Sets max_order_volume
     *
     * @param string|null $max_order_volume Maximum Order Volume
     *
     * @return $this
     */
    public function setMaxOrderVolume($max_order_volume)
    {
        $this->container['max_order_volume'] = $max_order_volume;

        return $this;
    }

    /**
     * Gets min_order_volume
     *
     * @return string|null
     */
    public function getMinOrderVolume()
    {
        return $this->container['min_order_volume'];
    }

    /**
     * Sets min_order_volume
     *
     * @param string|null $min_order_volume Minimum Order Volume
     *
     * @return $this
     */
    public function setMinOrderVolume($min_order_volume)
    {
        $this->container['min_order_volume'] = $min_order_volume;

        return $this;
    }

    /**
     * Gets leverage
     *
     * @return string|null
     */
    public function getLeverage()
    {
        return $this->container['leverage'];
    }

    /**
     * Sets leverage
     *
     * @param string|null $leverage Position leverage
     *
     * @return $this
     */
    public function setLeverage($leverage)
    {
        $this->container['leverage'] = $leverage;

        return $this;
    }

    /**
     * Gets price_precision
     *
     * @return int|null
     */
    public function getPricePrecision()
    {
        return $this->container['price_precision'];
    }

    /**
     * Sets price_precision
     *
     * @param int|null $price_precision Price precision (decimal places)
     *
     * @return $this
     */
    public function setPricePrecision($price_precision)
    {
        $this->container['price_precision'] = $price_precision;

        return $this;
    }

    /**
     * Gets price_sl_level
     *
     * @return string|null
     */
    public function getPriceSlLevel()
    {
        return $this->container['price_sl_level'];
    }

    /**
     * Sets price_sl_level
     *
     * @param string|null $price_sl_level Stop Loss Price Level
     *
     * @return $this
     */
    public function setPriceSlLevel($price_sl_level)
    {
        $this->container['price_sl_level'] = $price_sl_level;

        return $this;
    }

    /**
     * Gets swap_cost_type
     *
     * @return string|null
     */
    public function getSwapCostType()
    {
        return $this->container['swap_cost_type'];
    }

    /**
     * Sets swap_cost_type
     *
     * @param string|null $swap_cost_type Swap Cost Type
     *
     * @return $this
     */
    public function setSwapCostType($swap_cost_type)
    {
        $this->container['swap_cost_type'] = $swap_cost_type;

        return $this;
    }

    /**
     * Gets buy_swap_cost_rate
     *
     * @return string|null
     */
    public function getBuySwapCostRate()
    {
        return $this->container['buy_swap_cost_rate'];
    }

    /**
     * Sets buy_swap_cost_rate
     *
     * @param string|null $buy_swap_cost_rate Buy Swap Cost Rate
     *
     * @return $this
     */
    public function setBuySwapCostRate($buy_swap_cost_rate)
    {
        $this->container['buy_swap_cost_rate'] = $buy_swap_cost_rate;

        return $this;
    }

    /**
     * Gets sell_swap_cost_rate
     *
     * @return string|null
     */
    public function getSellSwapCostRate()
    {
        return $this->container['sell_swap_cost_rate'];
    }

    /**
     * Sets sell_swap_cost_rate
     *
     * @param string|null $sell_swap_cost_rate Sell Swap Cost Rate
     *
     * @return $this
     */
    public function setSellSwapCostRate($sell_swap_cost_rate)
    {
        $this->container['sell_swap_cost_rate'] = $sell_swap_cost_rate;

        return $this;
    }

    /**
     * Gets swap_cost_3day
     *
     * @return string|null
     */
    public function getSwapCost3day()
    {
        return $this->container['swap_cost_3day'];
    }

    /**
     * Sets swap_cost_3day
     *
     * @param string|null $swap_cost_3day 3-Day Swap Cost
     *
     * @return $this
     */
    public function setSwapCost3day($swap_cost_3day)
    {
        $this->container['swap_cost_3day'] = $swap_cost_3day;

        return $this;
    }

    /**
     * Gets trade_timezone
     *
     * @return string|null
     */
    public function getTradeTimezone()
    {
        return $this->container['trade_timezone'];
    }

    /**
     * Sets trade_timezone
     *
     * @param string|null $trade_timezone Trading Timezone
     *
     * @return $this
     */
    public function setTradeTimezone($trade_timezone)
    {
        $this->container['trade_timezone'] = $trade_timezone;

        return $this;
    }

    /**
     * Gets trade_mode
     *
     * @return string|null
     */
    public function getTradeMode()
    {
        return $this->container['trade_mode'];
    }

    /**
     * Sets trade_mode
     *
     * @param string|null $trade_mode Trading mode code (0=disabled, 1=long only, 2=short only, 3=close only, 4=full trading access)
     *
     * @return $this
     */
    public function setTradeMode($trade_mode)
    {
        $this->container['trade_mode'] = $trade_mode;

        return $this;
    }

    /**
     * Gets icon_link
     *
     * @return string|null
     */
    public function getIconLink()
    {
        return $this->container['icon_link'];
    }

    /**
     * Sets icon_link
     *
     * @param string|null $icon_link Symbol icon URL
     *
     * @return $this
     */
    public function setIconLink($icon_link)
    {
        $this->container['icon_link'] = $icon_link;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


