<?php
/**
 * ContractMartingaleCreateParams
 *
 * PHP version 7
 *
 * @category Class
 * @package  GateApi
 * @author   Gate
 * @link     https://www.gate.com
 */

/**
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: https://openapi-generator.tech
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */

namespace GateApi\Model;

use \ArrayAccess;
use \GateApi\ObjectSerializer;

/**
 * ContractMartingaleCreateParams Class Doc Comment
 *
 * @category Class
 * @description 合约马丁策略的创建参数。
 * @package  GateApi
 * @author   Gate
 * @link     https://www.gate.com
 */
class ContractMartingaleCreateParams implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ContractMartingaleCreateParams';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'invest_amount' => 'string',
        'price_deviation' => 'string',
        'max_orders' => 'int',
        'take_profit_ratio' => 'string',
        'direction' => '\GateApi\Model\ContractMartingaleDirection',
        'leverage' => 'string',
        'stop_loss_price' => 'string',
        'profit_sharing_ratio' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPIFormats = [
        'invest_amount' => null,
        'price_deviation' => null,
        'max_orders' => 'int32',
        'take_profit_ratio' => null,
        'direction' => null,
        'leverage' => null,
        'stop_loss_price' => null,
        'profit_sharing_ratio' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'invest_amount' => 'invest_amount',
        'price_deviation' => 'price_deviation',
        'max_orders' => 'max_orders',
        'take_profit_ratio' => 'take_profit_ratio',
        'direction' => 'direction',
        'leverage' => 'leverage',
        'stop_loss_price' => 'stop_loss_price',
        'profit_sharing_ratio' => 'profit_sharing_ratio'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'invest_amount' => 'setInvestAmount',
        'price_deviation' => 'setPriceDeviation',
        'max_orders' => 'setMaxOrders',
        'take_profit_ratio' => 'setTakeProfitRatio',
        'direction' => 'setDirection',
        'leverage' => 'setLeverage',
        'stop_loss_price' => 'setStopLossPrice',
        'profit_sharing_ratio' => 'setProfitSharingRatio'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'invest_amount' => 'getInvestAmount',
        'price_deviation' => 'getPriceDeviation',
        'max_orders' => 'getMaxOrders',
        'take_profit_ratio' => 'getTakeProfitRatio',
        'direction' => 'getDirection',
        'leverage' => 'getLeverage',
        'stop_loss_price' => 'getStopLossPrice',
        'profit_sharing_ratio' => 'getProfitSharingRatio'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['invest_amount'] = isset($data['invest_amount']) ? $data['invest_amount'] : null;
        $this->container['price_deviation'] = isset($data['price_deviation']) ? $data['price_deviation'] : null;
        $this->container['max_orders'] = isset($data['max_orders']) ? $data['max_orders'] : null;
        $this->container['take_profit_ratio'] = isset($data['take_profit_ratio']) ? $data['take_profit_ratio'] : null;
        $this->container['direction'] = isset($data['direction']) ? $data['direction'] : null;
        $this->container['leverage'] = isset($data['leverage']) ? $data['leverage'] : null;
        $this->container['stop_loss_price'] = isset($data['stop_loss_price']) ? $data['stop_loss_price'] : null;
        $this->container['profit_sharing_ratio'] = isset($data['profit_sharing_ratio']) ? $data['profit_sharing_ratio'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['invest_amount'] === null) {
            $invalidProperties[] = "'invest_amount' can't be null";
        }
        if ($this->container['price_deviation'] === null) {
            $invalidProperties[] = "'price_deviation' can't be null";
        }
        if ($this->container['max_orders'] === null) {
            $invalidProperties[] = "'max_orders' can't be null";
        }
        if (($this->container['max_orders'] < 1)) {
            $invalidProperties[] = "invalid value for 'max_orders', must be bigger than or equal to 1.";
        }

        if ($this->container['take_profit_ratio'] === null) {
            $invalidProperties[] = "'take_profit_ratio' can't be null";
        }
        if ($this->container['direction'] === null) {
            $invalidProperties[] = "'direction' can't be null";
        }
        if ($this->container['leverage'] === null) {
            $invalidProperties[] = "'leverage' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets invest_amount
     *
     * @return string
     */
    public function getInvestAmount()
    {
        return $this->container['invest_amount'];
    }

    /**
     * Sets invest_amount
     *
     * @param string $invest_amount invest_amount
     *
     * @return $this
     */
    public function setInvestAmount($invest_amount)
    {
        $this->container['invest_amount'] = $invest_amount;

        return $this;
    }

    /**
     * Gets price_deviation
     *
     * @return string
     */
    public function getPriceDeviation()
    {
        return $this->container['price_deviation'];
    }

    /**
     * Sets price_deviation
     *
     * @param string $price_deviation price_deviation
     *
     * @return $this
     */
    public function setPriceDeviation($price_deviation)
    {
        $this->container['price_deviation'] = $price_deviation;

        return $this;
    }

    /**
     * Gets max_orders
     *
     * @return int
     */
    public function getMaxOrders()
    {
        return $this->container['max_orders'];
    }

    /**
     * Sets max_orders
     *
     * @param int $max_orders max_orders
     *
     * @return $this
     */
    public function setMaxOrders($max_orders)
    {

        if (($max_orders < 1)) {
            throw new \InvalidArgumentException('invalid value for $max_orders when calling ContractMartingaleCreateParams., must be bigger than or equal to 1.');
        }

        $this->container['max_orders'] = $max_orders;

        return $this;
    }

    /**
     * Gets take_profit_ratio
     *
     * @return string
     */
    public function getTakeProfitRatio()
    {
        return $this->container['take_profit_ratio'];
    }

    /**
     * Sets take_profit_ratio
     *
     * @param string $take_profit_ratio take_profit_ratio
     *
     * @return $this
     */
    public function setTakeProfitRatio($take_profit_ratio)
    {
        $this->container['take_profit_ratio'] = $take_profit_ratio;

        return $this;
    }

    /**
     * Gets direction
     *
     * @return \GateApi\Model\ContractMartingaleDirection
     */
    public function getDirection()
    {
        return $this->container['direction'];
    }

    /**
     * Sets direction
     *
     * @param \GateApi\Model\ContractMartingaleDirection $direction direction
     *
     * @return $this
     */
    public function setDirection($direction)
    {
        $this->container['direction'] = $direction;

        return $this;
    }

    /**
     * Gets leverage
     *
     * @return string
     */
    public function getLeverage()
    {
        return $this->container['leverage'];
    }

    /**
     * Sets leverage
     *
     * @param string $leverage leverage
     *
     * @return $this
     */
    public function setLeverage($leverage)
    {
        $this->container['leverage'] = $leverage;

        return $this;
    }

    /**
     * Gets stop_loss_price
     *
     * @return string|null
     */
    public function getStopLossPrice()
    {
        return $this->container['stop_loss_price'];
    }

    /**
     * Sets stop_loss_price
     *
     * @param string|null $stop_loss_price stop_loss_price
     *
     * @return $this
     */
    public function setStopLossPrice($stop_loss_price)
    {
        $this->container['stop_loss_price'] = $stop_loss_price;

        return $this;
    }

    /**
     * Gets profit_sharing_ratio
     *
     * @return string|null
     */
    public function getProfitSharingRatio()
    {
        return $this->container['profit_sharing_ratio'];
    }

    /**
     * Sets profit_sharing_ratio
     *
     * @param string|null $profit_sharing_ratio profit_sharing_ratio
     *
     * @return $this
     */
    public function setProfitSharingRatio($profit_sharing_ratio)
    {
        $this->container['profit_sharing_ratio'] = $profit_sharing_ratio;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


