<?php
/**
 * FlashSwapMultiCurrencyPreviewParam
 *
 * PHP version 7
 *
 * @category Class
 * @package  GateApi
 * @author   Gate
 * @link     https://www.gate.com
 */

/**
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: https://openapi-generator.tech
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */

namespace GateApi\Model;

use \ArrayAccess;
use \GateApi\ObjectSerializer;

/**
 * FlashSwapMultiCurrencyPreviewParam Class Doc Comment
 *
 * @category Class
 * @package  GateApi
 * @author   Gate
 * @link     https://www.gate.com
 */
class FlashSwapMultiCurrencyPreviewParam implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'FlashSwapMultiCurrencyPreviewParam';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'sell_asset' => 'string',
        'sell_amount' => 'string',
        'buy_asset' => 'string',
        'buy_amount' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPIFormats = [
        'sell_asset' => null,
        'sell_amount' => null,
        'buy_asset' => null,
        'buy_amount' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'sell_asset' => 'sell_asset',
        'sell_amount' => 'sell_amount',
        'buy_asset' => 'buy_asset',
        'buy_amount' => 'buy_amount'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'sell_asset' => 'setSellAsset',
        'sell_amount' => 'setSellAmount',
        'buy_asset' => 'setBuyAsset',
        'buy_amount' => 'setBuyAmount'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'sell_asset' => 'getSellAsset',
        'sell_amount' => 'getSellAmount',
        'buy_asset' => 'getBuyAsset',
        'buy_amount' => 'getBuyAmount'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['sell_asset'] = isset($data['sell_asset']) ? $data['sell_asset'] : null;
        $this->container['sell_amount'] = isset($data['sell_amount']) ? $data['sell_amount'] : null;
        $this->container['buy_asset'] = isset($data['buy_asset']) ? $data['buy_asset'] : null;
        $this->container['buy_amount'] = isset($data['buy_amount']) ? $data['buy_amount'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['sell_asset'] === null) {
            $invalidProperties[] = "'sell_asset' can't be null";
        }
        if ($this->container['buy_asset'] === null) {
            $invalidProperties[] = "'buy_asset' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets sell_asset
     *
     * @return string
     */
    public function getSellAsset()
    {
        return $this->container['sell_asset'];
    }

    /**
     * Sets sell_asset
     *
     * @param string $sell_asset Currency to sell
     *
     * @return $this
     */
    public function setSellAsset($sell_asset)
    {
        $this->container['sell_asset'] = $sell_asset;

        return $this;
    }

    /**
     * Gets sell_amount
     *
     * @return string|null
     */
    public function getSellAmount()
    {
        return $this->container['sell_amount'];
    }

    /**
     * Sets sell_amount
     *
     * @param string|null $sell_amount Sell amount
     *
     * @return $this
     */
    public function setSellAmount($sell_amount)
    {
        $this->container['sell_amount'] = $sell_amount;

        return $this;
    }

    /**
     * Gets buy_asset
     *
     * @return string
     */
    public function getBuyAsset()
    {
        return $this->container['buy_asset'];
    }

    /**
     * Sets buy_asset
     *
     * @param string $buy_asset Currency to buy
     *
     * @return $this
     */
    public function setBuyAsset($buy_asset)
    {
        $this->container['buy_asset'] = $buy_asset;

        return $this;
    }

    /**
     * Gets buy_amount
     *
     * @return string|null
     */
    public function getBuyAmount()
    {
        return $this->container['buy_amount'];
    }

    /**
     * Sets buy_amount
     *
     * @param string|null $buy_amount Buy amount
     *
     * @return $this
     */
    public function setBuyAmount($buy_amount)
    {
        $this->container['buy_amount'] = $buy_amount;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


