<?php
/**
 * FuturesDirection
 *
 * PHP version 7
 *
 * @category Class
 * @package  GateApi
 * @author   Gate
 * @link     https://www.gate.com
 */

/**
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: https://openapi-generator.tech
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */

namespace GateApi\Model;
use \GateApi\ObjectSerializer;

/**
 * FuturesDirection Class Doc Comment
 *
 * @category Class
 * @description 合约类策略支持的方向枚举。
 * @package  GateApi
 * @author   Gate
 * @link     https://www.gate.com
 */
class FuturesDirection
{
    /**
     * Possible values of this enum
     */
    const LONG = 'long';
    const SHORT = 'short';
    const NEUTRAL = 'neutral';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::LONG,
            self::SHORT,
            self::NEUTRAL,
        ];
    }
}


