<?php
/**
 * HodlerAirdropV4UserAirdropRecord
 *
 * PHP version 7
 *
 * @category Class
 * @package  GateApi
 * @author   Gate
 * @link     https://www.gate.com
 */

/**
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: https://openapi-generator.tech
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */

namespace GateApi\Model;

use \ArrayAccess;
use \GateApi\ObjectSerializer;

/**
 * HodlerAirdropV4UserAirdropRecord Class Doc Comment
 *
 * @category Class
 * @description 用户空投发放记录单项
 * @package  GateApi
 * @author   Gate
 * @link     https://www.gate.com
 */
class HodlerAirdropV4UserAirdropRecord implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'HodlerAirdropV4UserAirdropRecord';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'hodler_id' => 'string',
        'asset' => 'string',
        'receive_amount_base' => 'string',
        'receive_amount_ext' => 'string',
        'delivery_timest' => 'string',
        'exchange' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPIFormats = [
        'hodler_id' => null,
        'asset' => null,
        'receive_amount_base' => null,
        'receive_amount_ext' => null,
        'delivery_timest' => null,
        'exchange' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'hodler_id' => 'hodler_id',
        'asset' => 'asset',
        'receive_amount_base' => 'receive_amount_base',
        'receive_amount_ext' => 'receive_amount_ext',
        'delivery_timest' => 'delivery_timest',
        'exchange' => 'exchange'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'hodler_id' => 'setHodlerId',
        'asset' => 'setAsset',
        'receive_amount_base' => 'setReceiveAmountBase',
        'receive_amount_ext' => 'setReceiveAmountExt',
        'delivery_timest' => 'setDeliveryTimest',
        'exchange' => 'setExchange'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'hodler_id' => 'getHodlerId',
        'asset' => 'getAsset',
        'receive_amount_base' => 'getReceiveAmountBase',
        'receive_amount_ext' => 'getReceiveAmountExt',
        'delivery_timest' => 'getDeliveryTimest',
        'exchange' => 'getExchange'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['hodler_id'] = isset($data['hodler_id']) ? $data['hodler_id'] : null;
        $this->container['asset'] = isset($data['asset']) ? $data['asset'] : null;
        $this->container['receive_amount_base'] = isset($data['receive_amount_base']) ? $data['receive_amount_base'] : null;
        $this->container['receive_amount_ext'] = isset($data['receive_amount_ext']) ? $data['receive_amount_ext'] : null;
        $this->container['delivery_timest'] = isset($data['delivery_timest']) ? $data['delivery_timest'] : null;
        $this->container['exchange'] = isset($data['exchange']) ? $data['exchange'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['hodler_id'] === null) {
            $invalidProperties[] = "'hodler_id' can't be null";
        }
        if ($this->container['asset'] === null) {
            $invalidProperties[] = "'asset' can't be null";
        }
        if ($this->container['delivery_timest'] === null) {
            $invalidProperties[] = "'delivery_timest' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets hodler_id
     *
     * @return string
     */
    public function getHodlerId()
    {
        return $this->container['hodler_id'];
    }

    /**
     * Sets hodler_id
     *
     * @param string $hodler_id Product ID
     *
     * @return $this
     */
    public function setHodlerId($hodler_id)
    {
        $this->container['hodler_id'] = $hodler_id;

        return $this;
    }

    /**
     * Gets asset
     *
     * @return string
     */
    public function getAsset()
    {
        return $this->container['asset'];
    }

    /**
     * Sets asset
     *
     * @param string $asset 空投币种
     *
     * @return $this
     */
    public function setAsset($asset)
    {
        $this->container['asset'] = $asset;

        return $this;
    }

    /**
     * Gets receive_amount_base
     *
     * @return string|null
     */
    public function getReceiveAmountBase()
    {
        return $this->container['receive_amount_base'];
    }

    /**
     * Sets receive_amount_base
     *
     * @param string|null $receive_amount_base 基础空投金额
     *
     * @return $this
     */
    public function setReceiveAmountBase($receive_amount_base)
    {
        $this->container['receive_amount_base'] = $receive_amount_base;

        return $this;
    }

    /**
     * Gets receive_amount_ext
     *
     * @return string|null
     */
    public function getReceiveAmountExt()
    {
        return $this->container['receive_amount_ext'];
    }

    /**
     * Sets receive_amount_ext
     *
     * @param string|null $receive_amount_ext 额外空投金额（余币宝加成）
     *
     * @return $this
     */
    public function setReceiveAmountExt($receive_amount_ext)
    {
        $this->container['receive_amount_ext'] = $receive_amount_ext;

        return $this;
    }

    /**
     * Gets delivery_timest
     *
     * @return string
     */
    public function getDeliveryTimest()
    {
        return $this->container['delivery_timest'];
    }

    /**
     * Sets delivery_timest
     *
     * @param string $delivery_timest 空投发放时间，格式 Y-m-d H:i:s，UTC；未发放时可能为空字符串
     *
     * @return $this
     */
    public function setDeliveryTimest($delivery_timest)
    {
        $this->container['delivery_timest'] = $delivery_timest;

        return $this;
    }

    /**
     * Gets exchange
     *
     * @return string|null
     */
    public function getExchange()
    {
        return $this->container['exchange'];
    }

    /**
     * Sets exchange
     *
     * @param string|null $exchange 自动兑换状态，0未兑换 1已兑换为GT
     *
     * @return $this
     */
    public function setExchange($exchange)
    {
        $this->container['exchange'] = $exchange;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


