<?php
/**
 * InlineResponse20044
 *
 * PHP version 7
 *
 * @category Class
 * @package  GateApi
 * @author   Gate
 * @link     https://www.gate.com
 */

/**
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: https://openapi-generator.tech
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */

namespace GateApi\Model;

use \ArrayAccess;
use \GateApi\ObjectSerializer;

/**
 * InlineResponse20044 Class Doc Comment
 *
 * @category Class
 * @package  GateApi
 * @author   Gate
 * @link     https://www.gate.com
 */
class InlineResponse20044 implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'inline_response_200_44';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'user_id' => 'string',
        'symbol' => 'string',
        'interest_id' => 'string',
        'liability_id' => 'string',
        'liability' => 'string',
        'liability_coin' => 'string',
        'interest' => 'string',
        'interest_rate' => 'string',
        'interest_type' => 'string',
        'create_time' => 'string',
        'exchange_type' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPIFormats = [
        'user_id' => null,
        'symbol' => null,
        'interest_id' => null,
        'liability_id' => null,
        'liability' => null,
        'liability_coin' => null,
        'interest' => null,
        'interest_rate' => null,
        'interest_type' => null,
        'create_time' => null,
        'exchange_type' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'user_id' => 'userId',
        'symbol' => 'symbol',
        'interest_id' => 'interest_id',
        'liability_id' => 'liability_id',
        'liability' => 'liability',
        'liability_coin' => 'liability_coin',
        'interest' => 'interest',
        'interest_rate' => 'interest_rate',
        'interest_type' => 'interest_type',
        'create_time' => 'create_time',
        'exchange_type' => 'exchange_type'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'user_id' => 'setUserId',
        'symbol' => 'setSymbol',
        'interest_id' => 'setInterestId',
        'liability_id' => 'setLiabilityId',
        'liability' => 'setLiability',
        'liability_coin' => 'setLiabilityCoin',
        'interest' => 'setInterest',
        'interest_rate' => 'setInterestRate',
        'interest_type' => 'setInterestType',
        'create_time' => 'setCreateTime',
        'exchange_type' => 'setExchangeType'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'user_id' => 'getUserId',
        'symbol' => 'getSymbol',
        'interest_id' => 'getInterestId',
        'liability_id' => 'getLiabilityId',
        'liability' => 'getLiability',
        'liability_coin' => 'getLiabilityCoin',
        'interest' => 'getInterest',
        'interest_rate' => 'getInterestRate',
        'interest_type' => 'getInterestType',
        'create_time' => 'getCreateTime',
        'exchange_type' => 'getExchangeType'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['user_id'] = isset($data['user_id']) ? $data['user_id'] : null;
        $this->container['symbol'] = isset($data['symbol']) ? $data['symbol'] : null;
        $this->container['interest_id'] = isset($data['interest_id']) ? $data['interest_id'] : null;
        $this->container['liability_id'] = isset($data['liability_id']) ? $data['liability_id'] : null;
        $this->container['liability'] = isset($data['liability']) ? $data['liability'] : null;
        $this->container['liability_coin'] = isset($data['liability_coin']) ? $data['liability_coin'] : null;
        $this->container['interest'] = isset($data['interest']) ? $data['interest'] : null;
        $this->container['interest_rate'] = isset($data['interest_rate']) ? $data['interest_rate'] : null;
        $this->container['interest_type'] = isset($data['interest_type']) ? $data['interest_type'] : null;
        $this->container['create_time'] = isset($data['create_time']) ? $data['create_time'] : null;
        $this->container['exchange_type'] = isset($data['exchange_type']) ? $data['exchange_type'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['user_id'] === null) {
            $invalidProperties[] = "'user_id' can't be null";
        }
        if ($this->container['symbol'] === null) {
            $invalidProperties[] = "'symbol' can't be null";
        }
        if ($this->container['interest_id'] === null) {
            $invalidProperties[] = "'interest_id' can't be null";
        }
        if ($this->container['liability_id'] === null) {
            $invalidProperties[] = "'liability_id' can't be null";
        }
        if ($this->container['liability'] === null) {
            $invalidProperties[] = "'liability' can't be null";
        }
        if ($this->container['liability_coin'] === null) {
            $invalidProperties[] = "'liability_coin' can't be null";
        }
        if ($this->container['interest'] === null) {
            $invalidProperties[] = "'interest' can't be null";
        }
        if ($this->container['interest_rate'] === null) {
            $invalidProperties[] = "'interest_rate' can't be null";
        }
        if ($this->container['interest_type'] === null) {
            $invalidProperties[] = "'interest_type' can't be null";
        }
        if ($this->container['create_time'] === null) {
            $invalidProperties[] = "'create_time' can't be null";
        }
        if ($this->container['exchange_type'] === null) {
            $invalidProperties[] = "'exchange_type' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets user_id
     *
     * @return string
     */
    public function getUserId()
    {
        return $this->container['user_id'];
    }

    /**
     * Sets user_id
     *
     * @param string $user_id User ID
     *
     * @return $this
     */
    public function setUserId($user_id)
    {
        $this->container['user_id'] = $user_id;

        return $this;
    }

    /**
     * Gets symbol
     *
     * @return string
     */
    public function getSymbol()
    {
        return $this->container['symbol'];
    }

    /**
     * Sets symbol
     *
     * @param string $symbol Trading Pair
     *
     * @return $this
     */
    public function setSymbol($symbol)
    {
        $this->container['symbol'] = $symbol;

        return $this;
    }

    /**
     * Gets interest_id
     *
     * @return string
     */
    public function getInterestId()
    {
        return $this->container['interest_id'];
    }

    /**
     * Sets interest_id
     *
     * @param string $interest_id Interest Deduction ID
     *
     * @return $this
     */
    public function setInterestId($interest_id)
    {
        $this->container['interest_id'] = $interest_id;

        return $this;
    }

    /**
     * Gets liability_id
     *
     * @return string
     */
    public function getLiabilityId()
    {
        return $this->container['liability_id'];
    }

    /**
     * Sets liability_id
     *
     * @param string $liability_id Debt Source ID, can be Order ID or Position ID
     *
     * @return $this
     */
    public function setLiabilityId($liability_id)
    {
        $this->container['liability_id'] = $liability_id;

        return $this;
    }

    /**
     * Gets liability
     *
     * @return string
     */
    public function getLiability()
    {
        return $this->container['liability'];
    }

    /**
     * Sets liability
     *
     * @param string $liability Debt Quantity
     *
     * @return $this
     */
    public function setLiability($liability)
    {
        $this->container['liability'] = $liability;

        return $this;
    }

    /**
     * Gets liability_coin
     *
     * @return string
     */
    public function getLiabilityCoin()
    {
        return $this->container['liability_coin'];
    }

    /**
     * Sets liability_coin
     *
     * @param string $liability_coin Debt Currency
     *
     * @return $this
     */
    public function setLiabilityCoin($liability_coin)
    {
        $this->container['liability_coin'] = $liability_coin;

        return $this;
    }

    /**
     * Gets interest
     *
     * @return string
     */
    public function getInterest()
    {
        return $this->container['interest'];
    }

    /**
     * Sets interest
     *
     * @param string $interest Interest
     *
     * @return $this
     */
    public function setInterest($interest)
    {
        $this->container['interest'] = $interest;

        return $this;
    }

    /**
     * Gets interest_rate
     *
     * @return string
     */
    public function getInterestRate()
    {
        return $this->container['interest_rate'];
    }

    /**
     * Sets interest_rate
     *
     * @param string $interest_rate interest rate
     *
     * @return $this
     */
    public function setInterestRate($interest_rate)
    {
        $this->container['interest_rate'] = $interest_rate;

        return $this;
    }

    /**
     * Gets interest_type
     *
     * @return string
     */
    public function getInterestType()
    {
        return $this->container['interest_type'];
    }

    /**
     * Sets interest_type
     *
     * @param string $interest_type Interest deduction type (`PERIODIC_POSITION`: periodic position interest; `PERIODIC_OPEN_ORDER`: periodic open-order interest; `IMMEDIATE_OPEN_ORDER`: interest charged on order opening)
     *
     * @return $this
     */
    public function setInterestType($interest_type)
    {
        $this->container['interest_type'] = $interest_type;

        return $this;
    }

    /**
     * Gets create_time
     *
     * @return string
     */
    public function getCreateTime()
    {
        return $this->container['create_time'];
    }

    /**
     * Sets create_time
     *
     * @param string $create_time Created time
     *
     * @return $this
     */
    public function setCreateTime($create_time)
    {
        $this->container['create_time'] = $create_time;

        return $this;
    }

    /**
     * Gets exchange_type
     *
     * @return string
     */
    public function getExchangeType()
    {
        return $this->container['exchange_type'];
    }

    /**
     * Sets exchange_type
     *
     * @param string $exchange_type Exchange
     *
     * @return $this
     */
    public function setExchangeType($exchange_type)
    {
        $this->container['exchange_type'] = $exchange_type;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


