<?php
/**
 * InlineResponse20012Data
 *
 * PHP version 7
 *
 * @category Class
 * @package  GateApi
 * @author   Gate
 * @link     https://www.gate.com
 */

/**
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: https://openapi-generator.tech
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */

namespace GateApi\Model;

use \ArrayAccess;
use \GateApi\ObjectSerializer;

/**
 * InlineResponse20012Data Class Doc Comment
 *
 * @category Class
 * @package  GateApi
 * @author   Gate
 * @link     https://www.gate.com
 */
class InlineResponse20012Data implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'inline_response_200_12_data';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'order_id' => 'string',
        'uid' => 'string',
        'type' => 'string',
        'fiat_currency' => 'string',
        'fiat_amount' => 'string',
        'crypto_currency' => 'string',
        'crypto_amount' => 'string',
        'rate' => 'string',
        'transfer_remark' => 'string',
        'status' => 'string',
        'db_status' => 'string',
        'create_time' => 'string',
        'memo' => 'string',
        'side' => 'string',
        'promotion_code' => 'string',
        'trade_no' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPIFormats = [
        'order_id' => null,
        'uid' => null,
        'type' => null,
        'fiat_currency' => null,
        'fiat_amount' => null,
        'crypto_currency' => null,
        'crypto_amount' => null,
        'rate' => null,
        'transfer_remark' => null,
        'status' => null,
        'db_status' => null,
        'create_time' => null,
        'memo' => null,
        'side' => null,
        'promotion_code' => null,
        'trade_no' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'order_id' => 'order_id',
        'uid' => 'uid',
        'type' => 'type',
        'fiat_currency' => 'fiat_currency',
        'fiat_amount' => 'fiat_amount',
        'crypto_currency' => 'crypto_currency',
        'crypto_amount' => 'crypto_amount',
        'rate' => 'rate',
        'transfer_remark' => 'transfer_remark',
        'status' => 'status',
        'db_status' => 'db_status',
        'create_time' => 'create_time',
        'memo' => 'memo',
        'side' => 'side',
        'promotion_code' => 'promotion_code',
        'trade_no' => 'trade_no'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'order_id' => 'setOrderId',
        'uid' => 'setUid',
        'type' => 'setType',
        'fiat_currency' => 'setFiatCurrency',
        'fiat_amount' => 'setFiatAmount',
        'crypto_currency' => 'setCryptoCurrency',
        'crypto_amount' => 'setCryptoAmount',
        'rate' => 'setRate',
        'transfer_remark' => 'setTransferRemark',
        'status' => 'setStatus',
        'db_status' => 'setDbStatus',
        'create_time' => 'setCreateTime',
        'memo' => 'setMemo',
        'side' => 'setSide',
        'promotion_code' => 'setPromotionCode',
        'trade_no' => 'setTradeNo'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'order_id' => 'getOrderId',
        'uid' => 'getUid',
        'type' => 'getType',
        'fiat_currency' => 'getFiatCurrency',
        'fiat_amount' => 'getFiatAmount',
        'crypto_currency' => 'getCryptoCurrency',
        'crypto_amount' => 'getCryptoAmount',
        'rate' => 'getRate',
        'transfer_remark' => 'getTransferRemark',
        'status' => 'getStatus',
        'db_status' => 'getDbStatus',
        'create_time' => 'getCreateTime',
        'memo' => 'getMemo',
        'side' => 'getSide',
        'promotion_code' => 'getPromotionCode',
        'trade_no' => 'getTradeNo'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['order_id'] = isset($data['order_id']) ? $data['order_id'] : null;
        $this->container['uid'] = isset($data['uid']) ? $data['uid'] : null;
        $this->container['type'] = isset($data['type']) ? $data['type'] : null;
        $this->container['fiat_currency'] = isset($data['fiat_currency']) ? $data['fiat_currency'] : null;
        $this->container['fiat_amount'] = isset($data['fiat_amount']) ? $data['fiat_amount'] : null;
        $this->container['crypto_currency'] = isset($data['crypto_currency']) ? $data['crypto_currency'] : null;
        $this->container['crypto_amount'] = isset($data['crypto_amount']) ? $data['crypto_amount'] : null;
        $this->container['rate'] = isset($data['rate']) ? $data['rate'] : null;
        $this->container['transfer_remark'] = isset($data['transfer_remark']) ? $data['transfer_remark'] : null;
        $this->container['status'] = isset($data['status']) ? $data['status'] : null;
        $this->container['db_status'] = isset($data['db_status']) ? $data['db_status'] : null;
        $this->container['create_time'] = isset($data['create_time']) ? $data['create_time'] : null;
        $this->container['memo'] = isset($data['memo']) ? $data['memo'] : null;
        $this->container['side'] = isset($data['side']) ? $data['side'] : null;
        $this->container['promotion_code'] = isset($data['promotion_code']) ? $data['promotion_code'] : null;
        $this->container['trade_no'] = isset($data['trade_no']) ? $data['trade_no'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['order_id'] === null) {
            $invalidProperties[] = "'order_id' can't be null";
        }
        if ($this->container['uid'] === null) {
            $invalidProperties[] = "'uid' can't be null";
        }
        if ($this->container['type'] === null) {
            $invalidProperties[] = "'type' can't be null";
        }
        if ($this->container['fiat_currency'] === null) {
            $invalidProperties[] = "'fiat_currency' can't be null";
        }
        if ($this->container['fiat_amount'] === null) {
            $invalidProperties[] = "'fiat_amount' can't be null";
        }
        if ($this->container['crypto_currency'] === null) {
            $invalidProperties[] = "'crypto_currency' can't be null";
        }
        if ($this->container['crypto_amount'] === null) {
            $invalidProperties[] = "'crypto_amount' can't be null";
        }
        if ($this->container['rate'] === null) {
            $invalidProperties[] = "'rate' can't be null";
        }
        if ($this->container['transfer_remark'] === null) {
            $invalidProperties[] = "'transfer_remark' can't be null";
        }
        if ($this->container['status'] === null) {
            $invalidProperties[] = "'status' can't be null";
        }
        if ($this->container['db_status'] === null) {
            $invalidProperties[] = "'db_status' can't be null";
        }
        if ($this->container['create_time'] === null) {
            $invalidProperties[] = "'create_time' can't be null";
        }
        if ($this->container['memo'] === null) {
            $invalidProperties[] = "'memo' can't be null";
        }
        if ($this->container['side'] === null) {
            $invalidProperties[] = "'side' can't be null";
        }
        if ($this->container['promotion_code'] === null) {
            $invalidProperties[] = "'promotion_code' can't be null";
        }
        if ($this->container['trade_no'] === null) {
            $invalidProperties[] = "'trade_no' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets order_id
     *
     * @return string
     */
    public function getOrderId()
    {
        return $this->container['order_id'];
    }

    /**
     * Sets order_id
     *
     * @param string $order_id Order ID
     *
     * @return $this
     */
    public function setOrderId($order_id)
    {
        $this->container['order_id'] = $order_id;

        return $this;
    }

    /**
     * Gets uid
     *
     * @return string
     */
    public function getUid()
    {
        return $this->container['uid'];
    }

    /**
     * Sets uid
     *
     * @param string $uid User ID
     *
     * @return $this
     */
    public function setUid($uid)
    {
        $this->container['uid'] = $uid;

        return $this;
    }

    /**
     * Gets type
     *
     * @return string
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param string $type Order Type
     *
     * @return $this
     */
    public function setType($type)
    {
        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets fiat_currency
     *
     * @return string
     */
    public function getFiatCurrency()
    {
        return $this->container['fiat_currency'];
    }

    /**
     * Sets fiat_currency
     *
     * @param string $fiat_currency Fiat type
     *
     * @return $this
     */
    public function setFiatCurrency($fiat_currency)
    {
        $this->container['fiat_currency'] = $fiat_currency;

        return $this;
    }

    /**
     * Gets fiat_amount
     *
     * @return string
     */
    public function getFiatAmount()
    {
        return $this->container['fiat_amount'];
    }

    /**
     * Sets fiat_amount
     *
     * @param string $fiat_amount Fiat amount
     *
     * @return $this
     */
    public function setFiatAmount($fiat_amount)
    {
        $this->container['fiat_amount'] = $fiat_amount;

        return $this;
    }

    /**
     * Gets crypto_currency
     *
     * @return string
     */
    public function getCryptoCurrency()
    {
        return $this->container['crypto_currency'];
    }

    /**
     * Sets crypto_currency
     *
     * @param string $crypto_currency Stablecoin
     *
     * @return $this
     */
    public function setCryptoCurrency($crypto_currency)
    {
        $this->container['crypto_currency'] = $crypto_currency;

        return $this;
    }

    /**
     * Gets crypto_amount
     *
     * @return string
     */
    public function getCryptoAmount()
    {
        return $this->container['crypto_amount'];
    }

    /**
     * Sets crypto_amount
     *
     * @param string $crypto_amount Stablecoin amount
     *
     * @return $this
     */
    public function setCryptoAmount($crypto_amount)
    {
        $this->container['crypto_amount'] = $crypto_amount;

        return $this;
    }

    /**
     * Gets rate
     *
     * @return string
     */
    public function getRate()
    {
        return $this->container['rate'];
    }

    /**
     * Sets rate
     *
     * @param string $rate Exchange rate
     *
     * @return $this
     */
    public function setRate($rate)
    {
        $this->container['rate'] = $rate;

        return $this;
    }

    /**
     * Gets transfer_remark
     *
     * @return string
     */
    public function getTransferRemark()
    {
        return $this->container['transfer_remark'];
    }

    /**
     * Sets transfer_remark
     *
     * @param string $transfer_remark Remark
     *
     * @return $this
     */
    public function setTransferRemark($transfer_remark)
    {
        $this->container['transfer_remark'] = $transfer_remark;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string $status Status
     *
     * @return $this
     */
    public function setStatus($status)
    {
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets db_status
     *
     * @return string
     */
    public function getDbStatus()
    {
        return $this->container['db_status'];
    }

    /**
     * Sets db_status
     *
     * @param string $db_status db_status
     *
     * @return $this
     */
    public function setDbStatus($db_status)
    {
        $this->container['db_status'] = $db_status;

        return $this;
    }

    /**
     * Gets create_time
     *
     * @return string
     */
    public function getCreateTime()
    {
        return $this->container['create_time'];
    }

    /**
     * Sets create_time
     *
     * @param string $create_time Created time
     *
     * @return $this
     */
    public function setCreateTime($create_time)
    {
        $this->container['create_time'] = $create_time;

        return $this;
    }

    /**
     * Gets memo
     *
     * @return string
     */
    public function getMemo()
    {
        return $this->container['memo'];
    }

    /**
     * Sets memo
     *
     * @param string $memo Cancellation or rejection reason
     *
     * @return $this
     */
    public function setMemo($memo)
    {
        $this->container['memo'] = $memo;

        return $this;
    }

    /**
     * Gets side
     *
     * @return string
     */
    public function getSide()
    {
        return $this->container['side'];
    }

    /**
     * Sets side
     *
     * @param string $side Quote direction
     *
     * @return $this
     */
    public function setSide($side)
    {
        $this->container['side'] = $side;

        return $this;
    }

    /**
     * Gets promotion_code
     *
     * @return string
     */
    public function getPromotionCode()
    {
        return $this->container['promotion_code'];
    }

    /**
     * Sets promotion_code
     *
     * @param string $promotion_code Promotion code
     *
     * @return $this
     */
    public function setPromotionCode($promotion_code)
    {
        $this->container['promotion_code'] = $promotion_code;

        return $this;
    }

    /**
     * Gets trade_no
     *
     * @return string
     */
    public function getTradeNo()
    {
        return $this->container['trade_no'];
    }

    /**
     * Sets trade_no
     *
     * @param string $trade_no Trade number
     *
     * @return $this
     */
    public function setTradeNo($trade_no)
    {
        $this->container['trade_no'] = $trade_no;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


