<?php
/**
 * InlineResponse20017DataMsgObj
 *
 * PHP version 7
 *
 * @category Class
 * @package  GateApi
 * @author   Gate
 * @link     https://www.gate.com
 */

/**
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: https://openapi-generator.tech
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */

namespace GateApi\Model;

use \ArrayAccess;
use \GateApi\ObjectSerializer;

/**
 * InlineResponse20017DataMsgObj Class Doc Comment
 *
 * @category Class
 * @package  GateApi
 * @author   Gate
 * @link     https://www.gate.com
 */
class InlineResponse20017DataMsgObj implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'inline_response_200_17_data_msg_obj';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'status' => 'string',
        'text' => 'string',
        'payment_voucher' => 'string[]',
        'reason_id' => 'int',
        'toast_id' => 'int',
        'reason_memo' => 'string',
        'cancel_time' => 'int',
        'seller_confirm' => 'int',
        'id' => 'string',
        'account_des' => 'string',
        'pay_type' => 'string',
        'file' => 'string',
        'file_key' => 'string',
        'account' => 'string',
        'memo' => 'string',
        'code' => 'string',
        'memo_ext' => 'string',
        'trade_tips' => 'string',
        'real_name' => 'string',
        'is_delete' => 'int',
        'pay_name' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPIFormats = [
        'status' => null,
        'text' => null,
        'payment_voucher' => null,
        'reason_id' => null,
        'toast_id' => null,
        'reason_memo' => null,
        'cancel_time' => null,
        'seller_confirm' => null,
        'id' => null,
        'account_des' => null,
        'pay_type' => null,
        'file' => null,
        'file_key' => null,
        'account' => null,
        'memo' => null,
        'code' => null,
        'memo_ext' => null,
        'trade_tips' => null,
        'real_name' => null,
        'is_delete' => null,
        'pay_name' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'status' => 'status',
        'text' => 'text',
        'payment_voucher' => 'payment_voucher',
        'reason_id' => 'reason_id',
        'toast_id' => 'toast_id',
        'reason_memo' => 'reason_memo',
        'cancel_time' => 'cancel_time',
        'seller_confirm' => 'seller_confirm',
        'id' => 'id',
        'account_des' => 'account_des',
        'pay_type' => 'pay_type',
        'file' => 'file',
        'file_key' => 'file_key',
        'account' => 'account',
        'memo' => 'memo',
        'code' => 'code',
        'memo_ext' => 'memo_ext',
        'trade_tips' => 'trade_tips',
        'real_name' => 'real_name',
        'is_delete' => 'is_delete',
        'pay_name' => 'pay_name'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'status' => 'setStatus',
        'text' => 'setText',
        'payment_voucher' => 'setPaymentVoucher',
        'reason_id' => 'setReasonId',
        'toast_id' => 'setToastId',
        'reason_memo' => 'setReasonMemo',
        'cancel_time' => 'setCancelTime',
        'seller_confirm' => 'setSellerConfirm',
        'id' => 'setId',
        'account_des' => 'setAccountDes',
        'pay_type' => 'setPayType',
        'file' => 'setFile',
        'file_key' => 'setFileKey',
        'account' => 'setAccount',
        'memo' => 'setMemo',
        'code' => 'setCode',
        'memo_ext' => 'setMemoExt',
        'trade_tips' => 'setTradeTips',
        'real_name' => 'setRealName',
        'is_delete' => 'setIsDelete',
        'pay_name' => 'setPayName'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'status' => 'getStatus',
        'text' => 'getText',
        'payment_voucher' => 'getPaymentVoucher',
        'reason_id' => 'getReasonId',
        'toast_id' => 'getToastId',
        'reason_memo' => 'getReasonMemo',
        'cancel_time' => 'getCancelTime',
        'seller_confirm' => 'getSellerConfirm',
        'id' => 'getId',
        'account_des' => 'getAccountDes',
        'pay_type' => 'getPayType',
        'file' => 'getFile',
        'file_key' => 'getFileKey',
        'account' => 'getAccount',
        'memo' => 'getMemo',
        'code' => 'getCode',
        'memo_ext' => 'getMemoExt',
        'trade_tips' => 'getTradeTips',
        'real_name' => 'getRealName',
        'is_delete' => 'getIsDelete',
        'pay_name' => 'getPayName'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['status'] = isset($data['status']) ? $data['status'] : null;
        $this->container['text'] = isset($data['text']) ? $data['text'] : null;
        $this->container['payment_voucher'] = isset($data['payment_voucher']) ? $data['payment_voucher'] : null;
        $this->container['reason_id'] = isset($data['reason_id']) ? $data['reason_id'] : null;
        $this->container['toast_id'] = isset($data['toast_id']) ? $data['toast_id'] : null;
        $this->container['reason_memo'] = isset($data['reason_memo']) ? $data['reason_memo'] : null;
        $this->container['cancel_time'] = isset($data['cancel_time']) ? $data['cancel_time'] : null;
        $this->container['seller_confirm'] = isset($data['seller_confirm']) ? $data['seller_confirm'] : null;
        $this->container['id'] = isset($data['id']) ? $data['id'] : null;
        $this->container['account_des'] = isset($data['account_des']) ? $data['account_des'] : null;
        $this->container['pay_type'] = isset($data['pay_type']) ? $data['pay_type'] : null;
        $this->container['file'] = isset($data['file']) ? $data['file'] : null;
        $this->container['file_key'] = isset($data['file_key']) ? $data['file_key'] : null;
        $this->container['account'] = isset($data['account']) ? $data['account'] : null;
        $this->container['memo'] = isset($data['memo']) ? $data['memo'] : null;
        $this->container['code'] = isset($data['code']) ? $data['code'] : null;
        $this->container['memo_ext'] = isset($data['memo_ext']) ? $data['memo_ext'] : null;
        $this->container['trade_tips'] = isset($data['trade_tips']) ? $data['trade_tips'] : null;
        $this->container['real_name'] = isset($data['real_name']) ? $data['real_name'] : null;
        $this->container['is_delete'] = isset($data['is_delete']) ? $data['is_delete'] : null;
        $this->container['pay_name'] = isset($data['pay_name']) ? $data['pay_name'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['account_des'] === null) {
            $invalidProperties[] = "'account_des' can't be null";
        }
        if ($this->container['pay_type'] === null) {
            $invalidProperties[] = "'pay_type' can't be null";
        }
        if ($this->container['file'] === null) {
            $invalidProperties[] = "'file' can't be null";
        }
        if ($this->container['file_key'] === null) {
            $invalidProperties[] = "'file_key' can't be null";
        }
        if ($this->container['account'] === null) {
            $invalidProperties[] = "'account' can't be null";
        }
        if ($this->container['memo'] === null) {
            $invalidProperties[] = "'memo' can't be null";
        }
        if ($this->container['code'] === null) {
            $invalidProperties[] = "'code' can't be null";
        }
        if ($this->container['memo_ext'] === null) {
            $invalidProperties[] = "'memo_ext' can't be null";
        }
        if ($this->container['trade_tips'] === null) {
            $invalidProperties[] = "'trade_tips' can't be null";
        }
        if ($this->container['real_name'] === null) {
            $invalidProperties[] = "'real_name' can't be null";
        }
        if ($this->container['is_delete'] === null) {
            $invalidProperties[] = "'is_delete' can't be null";
        }
        if ($this->container['pay_name'] === null) {
            $invalidProperties[] = "'pay_name' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets status
     *
     * @return string|null
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string|null $status Order status when message was sent
     *
     * @return $this
     */
    public function setStatus($status)
    {
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets text
     *
     * @return string|null
     */
    public function getText()
    {
        return $this->container['text'];
    }

    /**
     * Sets text
     *
     * @param string|null $text Message content
     *
     * @return $this
     */
    public function setText($text)
    {
        $this->container['text'] = $text;

        return $this;
    }

    /**
     * Gets payment_voucher
     *
     * @return string[]|null
     */
    public function getPaymentVoucher()
    {
        return $this->container['payment_voucher'];
    }

    /**
     * Sets payment_voucher
     *
     * @param string[]|null $payment_voucher Payment voucher
     *
     * @return $this
     */
    public function setPaymentVoucher($payment_voucher)
    {
        $this->container['payment_voucher'] = $payment_voucher;

        return $this;
    }

    /**
     * Gets reason_id
     *
     * @return int|null
     */
    public function getReasonId()
    {
        return $this->container['reason_id'];
    }

    /**
     * Sets reason_id
     *
     * @param int|null $reason_id Cancellation reason ID
     *
     * @return $this
     */
    public function setReasonId($reason_id)
    {
        $this->container['reason_id'] = $reason_id;

        return $this;
    }

    /**
     * Gets toast_id
     *
     * @return int|null
     */
    public function getToastId()
    {
        return $this->container['toast_id'];
    }

    /**
     * Sets toast_id
     *
     * @param int|null $toast_id Cancellation reason popup
     *
     * @return $this
     */
    public function setToastId($toast_id)
    {
        $this->container['toast_id'] = $toast_id;

        return $this;
    }

    /**
     * Gets reason_memo
     *
     * @return string|null
     */
    public function getReasonMemo()
    {
        return $this->container['reason_memo'];
    }

    /**
     * Sets reason_memo
     *
     * @param string|null $reason_memo Cancellation reason title
     *
     * @return $this
     */
    public function setReasonMemo($reason_memo)
    {
        $this->container['reason_memo'] = $reason_memo;

        return $this;
    }

    /**
     * Gets cancel_time
     *
     * @return int|null
     */
    public function getCancelTime()
    {
        return $this->container['cancel_time'];
    }

    /**
     * Sets cancel_time
     *
     * @param int|null $cancel_time Cancellation time
     *
     * @return $this
     */
    public function setCancelTime($cancel_time)
    {
        $this->container['cancel_time'] = $cancel_time;

        return $this;
    }

    /**
     * Gets seller_confirm
     *
     * @return int|null
     */
    public function getSellerConfirm()
    {
        return $this->container['seller_confirm'];
    }

    /**
     * Sets seller_confirm
     *
     * @param int|null $seller_confirm Whether seller confirmed the reason
     *
     * @return $this
     */
    public function setSellerConfirm($seller_confirm)
    {
        $this->container['seller_confirm'] = $seller_confirm;

        return $this;
    }

    /**
     * Gets id
     *
     * @return string
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string $id Payment method information ID
     *
     * @return $this
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets account_des
     *
     * @return string
     */
    public function getAccountDes()
    {
        return $this->container['account_des'];
    }

    /**
     * Sets account_des
     *
     * @param string $account_des Payment method description
     *
     * @return $this
     */
    public function setAccountDes($account_des)
    {
        $this->container['account_des'] = $account_des;

        return $this;
    }

    /**
     * Gets pay_type
     *
     * @return string
     */
    public function getPayType()
    {
        return $this->container['pay_type'];
    }

    /**
     * Sets pay_type
     *
     * @param string $pay_type Payment method type
     *
     * @return $this
     */
    public function setPayType($pay_type)
    {
        $this->container['pay_type'] = $pay_type;

        return $this;
    }

    /**
     * Gets file
     *
     * @return string
     */
    public function getFile()
    {
        return $this->container['file'];
    }

    /**
     * Sets file
     *
     * @param string $file Payment method file link
     *
     * @return $this
     */
    public function setFile($file)
    {
        $this->container['file'] = $file;

        return $this;
    }

    /**
     * Gets file_key
     *
     * @return string
     */
    public function getFileKey()
    {
        return $this->container['file_key'];
    }

    /**
     * Sets file_key
     *
     * @param string $file_key Payment method file key
     *
     * @return $this
     */
    public function setFileKey($file_key)
    {
        $this->container['file_key'] = $file_key;

        return $this;
    }

    /**
     * Gets account
     *
     * @return string
     */
    public function getAccount()
    {
        return $this->container['account'];
    }

    /**
     * Sets account
     *
     * @param string $account Payment method name
     *
     * @return $this
     */
    public function setAccount($account)
    {
        $this->container['account'] = $account;

        return $this;
    }

    /**
     * Gets memo
     *
     * @return string
     */
    public function getMemo()
    {
        return $this->container['memo'];
    }

    /**
     * Sets memo
     *
     * @param string $memo Payment method note
     *
     * @return $this
     */
    public function setMemo($memo)
    {
        $this->container['memo'] = $memo;

        return $this;
    }

    /**
     * Gets code
     *
     * @return string
     */
    public function getCode()
    {
        return $this->container['code'];
    }

    /**
     * Sets code
     *
     * @param string $code Payment method code
     *
     * @return $this
     */
    public function setCode($code)
    {
        $this->container['code'] = $code;

        return $this;
    }

    /**
     * Gets memo_ext
     *
     * @return string
     */
    public function getMemoExt()
    {
        return $this->container['memo_ext'];
    }

    /**
     * Sets memo_ext
     *
     * @param string $memo_ext Payment method additional note
     *
     * @return $this
     */
    public function setMemoExt($memo_ext)
    {
        $this->container['memo_ext'] = $memo_ext;

        return $this;
    }

    /**
     * Gets trade_tips
     *
     * @return string
     */
    public function getTradeTips()
    {
        return $this->container['trade_tips'];
    }

    /**
     * Sets trade_tips
     *
     * @param string $trade_tips Payment method tip
     *
     * @return $this
     */
    public function setTradeTips($trade_tips)
    {
        $this->container['trade_tips'] = $trade_tips;

        return $this;
    }

    /**
     * Gets real_name
     *
     * @return string
     */
    public function getRealName()
    {
        return $this->container['real_name'];
    }

    /**
     * Sets real_name
     *
     * @param string $real_name Payment method username
     *
     * @return $this
     */
    public function setRealName($real_name)
    {
        $this->container['real_name'] = $real_name;

        return $this;
    }

    /**
     * Gets is_delete
     *
     * @return int
     */
    public function getIsDelete()
    {
        return $this->container['is_delete'];
    }

    /**
     * Sets is_delete
     *
     * @param int $is_delete Whether deleted
     *
     * @return $this
     */
    public function setIsDelete($is_delete)
    {
        $this->container['is_delete'] = $is_delete;

        return $this;
    }

    /**
     * Gets pay_name
     *
     * @return string
     */
    public function getPayName()
    {
        return $this->container['pay_name'];
    }

    /**
     * Sets pay_name
     *
     * @param string $pay_name Payment method full name
     *
     * @return $this
     */
    public function setPayName($pay_name)
    {
        $this->container['pay_name'] = $pay_name;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


