<?php
/**
 * InlineResponse20031
 *
 * PHP version 7
 *
 * @category Class
 * @package  GateApi
 * @author   Gate
 * @link     https://www.gate.com
 */

/**
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: https://openapi-generator.tech
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */

namespace GateApi\Model;

use \ArrayAccess;
use \GateApi\ObjectSerializer;

/**
 * InlineResponse20031 Class Doc Comment
 *
 * @category Class
 * @package  GateApi
 * @author   Gate
 * @link     https://www.gate.com
 */
class InlineResponse20031 implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'inline_response_200_31';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'quote_id' => 'string',
        'valid_ms' => 'string',
        'from_coin' => 'string',
        'to_coin' => 'string',
        'from_amount' => 'string',
        'to_amount' => 'string',
        'price' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPIFormats = [
        'quote_id' => null,
        'valid_ms' => null,
        'from_coin' => null,
        'to_coin' => null,
        'from_amount' => null,
        'to_amount' => null,
        'price' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'quote_id' => 'quote_id',
        'valid_ms' => 'valid_ms',
        'from_coin' => 'from_coin',
        'to_coin' => 'to_coin',
        'from_amount' => 'from_amount',
        'to_amount' => 'to_amount',
        'price' => 'price'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'quote_id' => 'setQuoteId',
        'valid_ms' => 'setValidMs',
        'from_coin' => 'setFromCoin',
        'to_coin' => 'setToCoin',
        'from_amount' => 'setFromAmount',
        'to_amount' => 'setToAmount',
        'price' => 'setPrice'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'quote_id' => 'getQuoteId',
        'valid_ms' => 'getValidMs',
        'from_coin' => 'getFromCoin',
        'to_coin' => 'getToCoin',
        'from_amount' => 'getFromAmount',
        'to_amount' => 'getToAmount',
        'price' => 'getPrice'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['quote_id'] = isset($data['quote_id']) ? $data['quote_id'] : null;
        $this->container['valid_ms'] = isset($data['valid_ms']) ? $data['valid_ms'] : null;
        $this->container['from_coin'] = isset($data['from_coin']) ? $data['from_coin'] : null;
        $this->container['to_coin'] = isset($data['to_coin']) ? $data['to_coin'] : null;
        $this->container['from_amount'] = isset($data['from_amount']) ? $data['from_amount'] : null;
        $this->container['to_amount'] = isset($data['to_amount']) ? $data['to_amount'] : null;
        $this->container['price'] = isset($data['price']) ? $data['price'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['quote_id'] === null) {
            $invalidProperties[] = "'quote_id' can't be null";
        }
        if ($this->container['valid_ms'] === null) {
            $invalidProperties[] = "'valid_ms' can't be null";
        }
        if ($this->container['from_coin'] === null) {
            $invalidProperties[] = "'from_coin' can't be null";
        }
        if ($this->container['to_coin'] === null) {
            $invalidProperties[] = "'to_coin' can't be null";
        }
        if ($this->container['from_amount'] === null) {
            $invalidProperties[] = "'from_amount' can't be null";
        }
        if ($this->container['to_amount'] === null) {
            $invalidProperties[] = "'to_amount' can't be null";
        }
        if ($this->container['price'] === null) {
            $invalidProperties[] = "'price' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets quote_id
     *
     * @return string
     */
    public function getQuoteId()
    {
        return $this->container['quote_id'];
    }

    /**
     * Sets quote_id
     *
     * @param string $quote_id Quote ID
     *
     * @return $this
     */
    public function setQuoteId($quote_id)
    {
        $this->container['quote_id'] = $quote_id;

        return $this;
    }

    /**
     * Gets valid_ms
     *
     * @return string
     */
    public function getValidMs()
    {
        return $this->container['valid_ms'];
    }

    /**
     * Sets valid_ms
     *
     * @param string $valid_ms Valid time (milliseconds timestamp)
     *
     * @return $this
     */
    public function setValidMs($valid_ms)
    {
        $this->container['valid_ms'] = $valid_ms;

        return $this;
    }

    /**
     * Gets from_coin
     *
     * @return string
     */
    public function getFromCoin()
    {
        return $this->container['from_coin'];
    }

    /**
     * Sets from_coin
     *
     * @param string $from_coin Asset Sold
     *
     * @return $this
     */
    public function setFromCoin($from_coin)
    {
        $this->container['from_coin'] = $from_coin;

        return $this;
    }

    /**
     * Gets to_coin
     *
     * @return string
     */
    public function getToCoin()
    {
        return $this->container['to_coin'];
    }

    /**
     * Sets to_coin
     *
     * @param string $to_coin Asset Bought
     *
     * @return $this
     */
    public function setToCoin($to_coin)
    {
        $this->container['to_coin'] = $to_coin;

        return $this;
    }

    /**
     * Gets from_amount
     *
     * @return string
     */
    public function getFromAmount()
    {
        return $this->container['from_amount'];
    }

    /**
     * Sets from_amount
     *
     * @param string $from_amount Amount to sell
     *
     * @return $this
     */
    public function setFromAmount($from_amount)
    {
        $this->container['from_amount'] = $from_amount;

        return $this;
    }

    /**
     * Gets to_amount
     *
     * @return string
     */
    public function getToAmount()
    {
        return $this->container['to_amount'];
    }

    /**
     * Sets to_amount
     *
     * @param string $to_amount Amount to buy
     *
     * @return $this
     */
    public function setToAmount($to_amount)
    {
        $this->container['to_amount'] = $to_amount;

        return $this;
    }

    /**
     * Gets price
     *
     * @return string
     */
    public function getPrice()
    {
        return $this->container['price'];
    }

    /**
     * Sets price
     *
     * @param string $price Price
     *
     * @return $this
     */
    public function setPrice($price)
    {
        $this->container['price'] = $price;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


