<?php
/**
 * InlineResponse20014Data
 *
 * PHP version 7
 *
 * @category Class
 * @package  GateApi
 * @author   Gate
 * @link     https://www.gate.com
 */

/**
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: https://openapi-generator.tech
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */

namespace GateApi\Model;

use \ArrayAccess;
use \GateApi\ObjectSerializer;

/**
 * InlineResponse20014Data Class Doc Comment
 *
 * @category Class
 * @package  GateApi
 * @author   Gate
 * @link     https://www.gate.com
 */
class InlineResponse20014Data implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'inline_response_200_14_data';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'user_timest' => 'string',
        'email_verified' => 'string',
        'verified' => 'string',
        'has_phone' => 'string',
        'user_name' => 'string',
        'user_note' => 'string',
        'complete_transactions' => 'string',
        'paid_transactions' => 'string',
        'accepted_transactions' => 'string',
        'transactions_used_time' => 'string',
        'cancelled_used_time_month' => 'string',
        'complete_transactions_month' => 'string',
        'complete_rate_month' => 'int',
        'is_follow' => 'int',
        'have_traded' => 'int',
        'biz_uid' => 'string',
        'registration_days' => 'int',
        'first_trade_days' => 'int',
        'trade_versatile' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPIFormats = [
        'user_timest' => null,
        'email_verified' => null,
        'verified' => null,
        'has_phone' => null,
        'user_name' => null,
        'user_note' => null,
        'complete_transactions' => null,
        'paid_transactions' => null,
        'accepted_transactions' => null,
        'transactions_used_time' => null,
        'cancelled_used_time_month' => null,
        'complete_transactions_month' => null,
        'complete_rate_month' => null,
        'is_follow' => null,
        'have_traded' => null,
        'biz_uid' => null,
        'registration_days' => null,
        'first_trade_days' => null,
        'trade_versatile' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'user_timest' => 'user_timest',
        'email_verified' => 'email_verified',
        'verified' => 'verified',
        'has_phone' => 'has_phone',
        'user_name' => 'user_name',
        'user_note' => 'user_note',
        'complete_transactions' => 'complete_transactions',
        'paid_transactions' => 'paid_transactions',
        'accepted_transactions' => 'accepted_transactions',
        'transactions_used_time' => 'transactions_used_time',
        'cancelled_used_time_month' => 'cancelled_used_time_month',
        'complete_transactions_month' => 'complete_transactions_month',
        'complete_rate_month' => 'complete_rate_month',
        'is_follow' => 'is_follow',
        'have_traded' => 'have_traded',
        'biz_uid' => 'biz_uid',
        'registration_days' => 'registration_days',
        'first_trade_days' => 'first_trade_days',
        'trade_versatile' => 'trade_versatile'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'user_timest' => 'setUserTimest',
        'email_verified' => 'setEmailVerified',
        'verified' => 'setVerified',
        'has_phone' => 'setHasPhone',
        'user_name' => 'setUserName',
        'user_note' => 'setUserNote',
        'complete_transactions' => 'setCompleteTransactions',
        'paid_transactions' => 'setPaidTransactions',
        'accepted_transactions' => 'setAcceptedTransactions',
        'transactions_used_time' => 'setTransactionsUsedTime',
        'cancelled_used_time_month' => 'setCancelledUsedTimeMonth',
        'complete_transactions_month' => 'setCompleteTransactionsMonth',
        'complete_rate_month' => 'setCompleteRateMonth',
        'is_follow' => 'setIsFollow',
        'have_traded' => 'setHaveTraded',
        'biz_uid' => 'setBizUid',
        'registration_days' => 'setRegistrationDays',
        'first_trade_days' => 'setFirstTradeDays',
        'trade_versatile' => 'setTradeVersatile'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'user_timest' => 'getUserTimest',
        'email_verified' => 'getEmailVerified',
        'verified' => 'getVerified',
        'has_phone' => 'getHasPhone',
        'user_name' => 'getUserName',
        'user_note' => 'getUserNote',
        'complete_transactions' => 'getCompleteTransactions',
        'paid_transactions' => 'getPaidTransactions',
        'accepted_transactions' => 'getAcceptedTransactions',
        'transactions_used_time' => 'getTransactionsUsedTime',
        'cancelled_used_time_month' => 'getCancelledUsedTimeMonth',
        'complete_transactions_month' => 'getCompleteTransactionsMonth',
        'complete_rate_month' => 'getCompleteRateMonth',
        'is_follow' => 'getIsFollow',
        'have_traded' => 'getHaveTraded',
        'biz_uid' => 'getBizUid',
        'registration_days' => 'getRegistrationDays',
        'first_trade_days' => 'getFirstTradeDays',
        'trade_versatile' => 'getTradeVersatile'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['user_timest'] = isset($data['user_timest']) ? $data['user_timest'] : null;
        $this->container['email_verified'] = isset($data['email_verified']) ? $data['email_verified'] : null;
        $this->container['verified'] = isset($data['verified']) ? $data['verified'] : null;
        $this->container['has_phone'] = isset($data['has_phone']) ? $data['has_phone'] : null;
        $this->container['user_name'] = isset($data['user_name']) ? $data['user_name'] : null;
        $this->container['user_note'] = isset($data['user_note']) ? $data['user_note'] : null;
        $this->container['complete_transactions'] = isset($data['complete_transactions']) ? $data['complete_transactions'] : null;
        $this->container['paid_transactions'] = isset($data['paid_transactions']) ? $data['paid_transactions'] : null;
        $this->container['accepted_transactions'] = isset($data['accepted_transactions']) ? $data['accepted_transactions'] : null;
        $this->container['transactions_used_time'] = isset($data['transactions_used_time']) ? $data['transactions_used_time'] : null;
        $this->container['cancelled_used_time_month'] = isset($data['cancelled_used_time_month']) ? $data['cancelled_used_time_month'] : null;
        $this->container['complete_transactions_month'] = isset($data['complete_transactions_month']) ? $data['complete_transactions_month'] : null;
        $this->container['complete_rate_month'] = isset($data['complete_rate_month']) ? $data['complete_rate_month'] : null;
        $this->container['is_follow'] = isset($data['is_follow']) ? $data['is_follow'] : null;
        $this->container['have_traded'] = isset($data['have_traded']) ? $data['have_traded'] : null;
        $this->container['biz_uid'] = isset($data['biz_uid']) ? $data['biz_uid'] : null;
        $this->container['registration_days'] = isset($data['registration_days']) ? $data['registration_days'] : null;
        $this->container['first_trade_days'] = isset($data['first_trade_days']) ? $data['first_trade_days'] : null;
        $this->container['trade_versatile'] = isset($data['trade_versatile']) ? $data['trade_versatile'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['user_timest'] === null) {
            $invalidProperties[] = "'user_timest' can't be null";
        }
        if ($this->container['email_verified'] === null) {
            $invalidProperties[] = "'email_verified' can't be null";
        }
        if ($this->container['verified'] === null) {
            $invalidProperties[] = "'verified' can't be null";
        }
        if ($this->container['has_phone'] === null) {
            $invalidProperties[] = "'has_phone' can't be null";
        }
        if ($this->container['user_name'] === null) {
            $invalidProperties[] = "'user_name' can't be null";
        }
        if ($this->container['user_note'] === null) {
            $invalidProperties[] = "'user_note' can't be null";
        }
        if ($this->container['complete_transactions'] === null) {
            $invalidProperties[] = "'complete_transactions' can't be null";
        }
        if ($this->container['paid_transactions'] === null) {
            $invalidProperties[] = "'paid_transactions' can't be null";
        }
        if ($this->container['accepted_transactions'] === null) {
            $invalidProperties[] = "'accepted_transactions' can't be null";
        }
        if ($this->container['transactions_used_time'] === null) {
            $invalidProperties[] = "'transactions_used_time' can't be null";
        }
        if ($this->container['cancelled_used_time_month'] === null) {
            $invalidProperties[] = "'cancelled_used_time_month' can't be null";
        }
        if ($this->container['complete_transactions_month'] === null) {
            $invalidProperties[] = "'complete_transactions_month' can't be null";
        }
        if ($this->container['complete_rate_month'] === null) {
            $invalidProperties[] = "'complete_rate_month' can't be null";
        }
        if ($this->container['is_follow'] === null) {
            $invalidProperties[] = "'is_follow' can't be null";
        }
        if ($this->container['have_traded'] === null) {
            $invalidProperties[] = "'have_traded' can't be null";
        }
        if ($this->container['biz_uid'] === null) {
            $invalidProperties[] = "'biz_uid' can't be null";
        }
        if ($this->container['registration_days'] === null) {
            $invalidProperties[] = "'registration_days' can't be null";
        }
        if ($this->container['first_trade_days'] === null) {
            $invalidProperties[] = "'first_trade_days' can't be null";
        }
        if ($this->container['trade_versatile'] === null) {
            $invalidProperties[] = "'trade_versatile' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets user_timest
     *
     * @return string
     */
    public function getUserTimest()
    {
        return $this->container['user_timest'];
    }

    /**
     * Sets user_timest
     *
     * @param string $user_timest User registration time (formatted string)
     *
     * @return $this
     */
    public function setUserTimest($user_timest)
    {
        $this->container['user_timest'] = $user_timest;

        return $this;
    }

    /**
     * Gets email_verified
     *
     * @return string
     */
    public function getEmailVerified()
    {
        return $this->container['email_verified'];
    }

    /**
     * Sets email_verified
     *
     * @param string $email_verified Whether email is verified
     *
     * @return $this
     */
    public function setEmailVerified($email_verified)
    {
        $this->container['email_verified'] = $email_verified;

        return $this;
    }

    /**
     * Gets verified
     *
     * @return string
     */
    public function getVerified()
    {
        return $this->container['verified'];
    }

    /**
     * Sets verified
     *
     * @param string $verified Whether KYC verification is completed
     *
     * @return $this
     */
    public function setVerified($verified)
    {
        $this->container['verified'] = $verified;

        return $this;
    }

    /**
     * Gets has_phone
     *
     * @return string
     */
    public function getHasPhone()
    {
        return $this->container['has_phone'];
    }

    /**
     * Sets has_phone
     *
     * @param string $has_phone Whether phone is bound
     *
     * @return $this
     */
    public function setHasPhone($has_phone)
    {
        $this->container['has_phone'] = $has_phone;

        return $this;
    }

    /**
     * Gets user_name
     *
     * @return string
     */
    public function getUserName()
    {
        return $this->container['user_name'];
    }

    /**
     * Sets user_name
     *
     * @param string $user_name Username
     *
     * @return $this
     */
    public function setUserName($user_name)
    {
        $this->container['user_name'] = $user_name;

        return $this;
    }

    /**
     * Gets user_note
     *
     * @return string
     */
    public function getUserNote()
    {
        return $this->container['user_note'];
    }

    /**
     * Sets user_note
     *
     * @param string $user_note User note information
     *
     * @return $this
     */
    public function setUserNote($user_note)
    {
        $this->container['user_note'] = $user_note;

        return $this;
    }

    /**
     * Gets complete_transactions
     *
     * @return string
     */
    public function getCompleteTransactions()
    {
        return $this->container['complete_transactions'];
    }

    /**
     * Sets complete_transactions
     *
     * @param string $complete_transactions Total completed orders
     *
     * @return $this
     */
    public function setCompleteTransactions($complete_transactions)
    {
        $this->container['complete_transactions'] = $complete_transactions;

        return $this;
    }

    /**
     * Gets paid_transactions
     *
     * @return string
     */
    public function getPaidTransactions()
    {
        return $this->container['paid_transactions'];
    }

    /**
     * Sets paid_transactions
     *
     * @param string $paid_transactions Number of completed buy orders
     *
     * @return $this
     */
    public function setPaidTransactions($paid_transactions)
    {
        $this->container['paid_transactions'] = $paid_transactions;

        return $this;
    }

    /**
     * Gets accepted_transactions
     *
     * @return string
     */
    public function getAcceptedTransactions()
    {
        return $this->container['accepted_transactions'];
    }

    /**
     * Sets accepted_transactions
     *
     * @param string $accepted_transactions Number of completed sell orders
     *
     * @return $this
     */
    public function setAcceptedTransactions($accepted_transactions)
    {
        $this->container['accepted_transactions'] = $accepted_transactions;

        return $this;
    }

    /**
     * Gets transactions_used_time
     *
     * @return string
     */
    public function getTransactionsUsedTime()
    {
        return $this->container['transactions_used_time'];
    }

    /**
     * Sets transactions_used_time
     *
     * @param string $transactions_used_time Average time to confirm receipt
     *
     * @return $this
     */
    public function setTransactionsUsedTime($transactions_used_time)
    {
        $this->container['transactions_used_time'] = $transactions_used_time;

        return $this;
    }

    /**
     * Gets cancelled_used_time_month
     *
     * @return string
     */
    public function getCancelledUsedTimeMonth()
    {
        return $this->container['cancelled_used_time_month'];
    }

    /**
     * Sets cancelled_used_time_month
     *
     * @param string $cancelled_used_time_month Cancellation time in last 30 days
     *
     * @return $this
     */
    public function setCancelledUsedTimeMonth($cancelled_used_time_month)
    {
        $this->container['cancelled_used_time_month'] = $cancelled_used_time_month;

        return $this;
    }

    /**
     * Gets complete_transactions_month
     *
     * @return string
     */
    public function getCompleteTransactionsMonth()
    {
        return $this->container['complete_transactions_month'];
    }

    /**
     * Sets complete_transactions_month
     *
     * @param string $complete_transactions_month Number of completed orders in last 30 days
     *
     * @return $this
     */
    public function setCompleteTransactionsMonth($complete_transactions_month)
    {
        $this->container['complete_transactions_month'] = $complete_transactions_month;

        return $this;
    }

    /**
     * Gets complete_rate_month
     *
     * @return int
     */
    public function getCompleteRateMonth()
    {
        return $this->container['complete_rate_month'];
    }

    /**
     * Sets complete_rate_month
     *
     * @param int $complete_rate_month Completion rate in last 30 days
     *
     * @return $this
     */
    public function setCompleteRateMonth($complete_rate_month)
    {
        $this->container['complete_rate_month'] = $complete_rate_month;

        return $this;
    }

    /**
     * Gets is_follow
     *
     * @return int
     */
    public function getIsFollow()
    {
        return $this->container['is_follow'];
    }

    /**
     * Sets is_follow
     *
     * @param int $is_follow Whether following
     *
     * @return $this
     */
    public function setIsFollow($is_follow)
    {
        $this->container['is_follow'] = $is_follow;

        return $this;
    }

    /**
     * Gets have_traded
     *
     * @return int
     */
    public function getHaveTraded()
    {
        return $this->container['have_traded'];
    }

    /**
     * Sets have_traded
     *
     * @param int $have_traded Whether traded with self
     *
     * @return $this
     */
    public function setHaveTraded($have_traded)
    {
        $this->container['have_traded'] = $have_traded;

        return $this;
    }

    /**
     * Gets biz_uid
     *
     * @return string
     */
    public function getBizUid()
    {
        return $this->container['biz_uid'];
    }

    /**
     * Sets biz_uid
     *
     * @param string $biz_uid Encrypted UID
     *
     * @return $this
     */
    public function setBizUid($biz_uid)
    {
        $this->container['biz_uid'] = $biz_uid;

        return $this;
    }

    /**
     * Gets registration_days
     *
     * @return int
     */
    public function getRegistrationDays()
    {
        return $this->container['registration_days'];
    }

    /**
     * Sets registration_days
     *
     * @param int $registration_days Registration days
     *
     * @return $this
     */
    public function setRegistrationDays($registration_days)
    {
        $this->container['registration_days'] = $registration_days;

        return $this;
    }

    /**
     * Gets first_trade_days
     *
     * @return int
     */
    public function getFirstTradeDays()
    {
        return $this->container['first_trade_days'];
    }

    /**
     * Sets first_trade_days
     *
     * @param int $first_trade_days Days since first trade
     *
     * @return $this
     */
    public function setFirstTradeDays($first_trade_days)
    {
        $this->container['first_trade_days'] = $first_trade_days;

        return $this;
    }

    /**
     * Gets trade_versatile
     *
     * @return bool
     */
    public function getTradeVersatile()
    {
        return $this->container['trade_versatile'];
    }

    /**
     * Sets trade_versatile
     *
     * @param bool $trade_versatile Single user or composite user
     *
     * @return $this
     */
    public function setTradeVersatile($trade_versatile)
    {
        $this->container['trade_versatile'] = $trade_versatile;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


