<?php
/**
 * InlineResponse20038
 *
 * PHP version 7
 *
 * @category Class
 * @package  GateApi
 * @author   Gate
 * @link     https://www.gate.com
 */

/**
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: https://openapi-generator.tech
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */

namespace GateApi\Model;

use \ArrayAccess;
use \GateApi\ObjectSerializer;

/**
 * InlineResponse20038 Class Doc Comment
 *
 * @category Class
 * @package  GateApi
 * @author   Gate
 * @link     https://www.gate.com
 */
class InlineResponse20038 implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'inline_response_200_38';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'user_id' => 'string',
        'position_id' => 'string',
        'symbol' => 'string',
        'position_side' => 'string',
        'initial_margin' => 'string',
        'maintenance_margin' => 'string',
        'position_qty' => 'string',
        'position_value' => 'string',
        'upnl' => 'string',
        'upnl_rate' => 'string',
        'entry_price' => 'string',
        'mark_price' => 'string',
        'leverage' => 'string',
        'max_leverage' => 'string',
        'risk_limit' => 'string',
        'fee' => 'string',
        'funding_fee' => 'string',
        'funding_time' => 'string',
        'create_time' => 'string',
        'update_time' => 'string',
        'closed_pnl' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPIFormats = [
        'user_id' => null,
        'position_id' => null,
        'symbol' => null,
        'position_side' => null,
        'initial_margin' => null,
        'maintenance_margin' => null,
        'position_qty' => null,
        'position_value' => null,
        'upnl' => null,
        'upnl_rate' => null,
        'entry_price' => null,
        'mark_price' => null,
        'leverage' => null,
        'max_leverage' => null,
        'risk_limit' => null,
        'fee' => null,
        'funding_fee' => null,
        'funding_time' => null,
        'create_time' => null,
        'update_time' => null,
        'closed_pnl' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'user_id' => 'user_id',
        'position_id' => 'position_id',
        'symbol' => 'symbol',
        'position_side' => 'position_side',
        'initial_margin' => 'initial_margin',
        'maintenance_margin' => 'maintenance_margin',
        'position_qty' => 'position_qty',
        'position_value' => 'position_value',
        'upnl' => 'upnl',
        'upnl_rate' => 'upnl_rate',
        'entry_price' => 'entry_price',
        'mark_price' => 'mark_price',
        'leverage' => 'leverage',
        'max_leverage' => 'max_leverage',
        'risk_limit' => 'risk_limit',
        'fee' => 'fee',
        'funding_fee' => 'funding_fee',
        'funding_time' => 'funding_time',
        'create_time' => 'create_time',
        'update_time' => 'update_time',
        'closed_pnl' => 'closed_pnl'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'user_id' => 'setUserId',
        'position_id' => 'setPositionId',
        'symbol' => 'setSymbol',
        'position_side' => 'setPositionSide',
        'initial_margin' => 'setInitialMargin',
        'maintenance_margin' => 'setMaintenanceMargin',
        'position_qty' => 'setPositionQty',
        'position_value' => 'setPositionValue',
        'upnl' => 'setUpnl',
        'upnl_rate' => 'setUpnlRate',
        'entry_price' => 'setEntryPrice',
        'mark_price' => 'setMarkPrice',
        'leverage' => 'setLeverage',
        'max_leverage' => 'setMaxLeverage',
        'risk_limit' => 'setRiskLimit',
        'fee' => 'setFee',
        'funding_fee' => 'setFundingFee',
        'funding_time' => 'setFundingTime',
        'create_time' => 'setCreateTime',
        'update_time' => 'setUpdateTime',
        'closed_pnl' => 'setClosedPnl'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'user_id' => 'getUserId',
        'position_id' => 'getPositionId',
        'symbol' => 'getSymbol',
        'position_side' => 'getPositionSide',
        'initial_margin' => 'getInitialMargin',
        'maintenance_margin' => 'getMaintenanceMargin',
        'position_qty' => 'getPositionQty',
        'position_value' => 'getPositionValue',
        'upnl' => 'getUpnl',
        'upnl_rate' => 'getUpnlRate',
        'entry_price' => 'getEntryPrice',
        'mark_price' => 'getMarkPrice',
        'leverage' => 'getLeverage',
        'max_leverage' => 'getMaxLeverage',
        'risk_limit' => 'getRiskLimit',
        'fee' => 'getFee',
        'funding_fee' => 'getFundingFee',
        'funding_time' => 'getFundingTime',
        'create_time' => 'getCreateTime',
        'update_time' => 'getUpdateTime',
        'closed_pnl' => 'getClosedPnl'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['user_id'] = isset($data['user_id']) ? $data['user_id'] : null;
        $this->container['position_id'] = isset($data['position_id']) ? $data['position_id'] : null;
        $this->container['symbol'] = isset($data['symbol']) ? $data['symbol'] : null;
        $this->container['position_side'] = isset($data['position_side']) ? $data['position_side'] : null;
        $this->container['initial_margin'] = isset($data['initial_margin']) ? $data['initial_margin'] : null;
        $this->container['maintenance_margin'] = isset($data['maintenance_margin']) ? $data['maintenance_margin'] : null;
        $this->container['position_qty'] = isset($data['position_qty']) ? $data['position_qty'] : null;
        $this->container['position_value'] = isset($data['position_value']) ? $data['position_value'] : null;
        $this->container['upnl'] = isset($data['upnl']) ? $data['upnl'] : null;
        $this->container['upnl_rate'] = isset($data['upnl_rate']) ? $data['upnl_rate'] : null;
        $this->container['entry_price'] = isset($data['entry_price']) ? $data['entry_price'] : null;
        $this->container['mark_price'] = isset($data['mark_price']) ? $data['mark_price'] : null;
        $this->container['leverage'] = isset($data['leverage']) ? $data['leverage'] : null;
        $this->container['max_leverage'] = isset($data['max_leverage']) ? $data['max_leverage'] : null;
        $this->container['risk_limit'] = isset($data['risk_limit']) ? $data['risk_limit'] : null;
        $this->container['fee'] = isset($data['fee']) ? $data['fee'] : null;
        $this->container['funding_fee'] = isset($data['funding_fee']) ? $data['funding_fee'] : null;
        $this->container['funding_time'] = isset($data['funding_time']) ? $data['funding_time'] : null;
        $this->container['create_time'] = isset($data['create_time']) ? $data['create_time'] : null;
        $this->container['update_time'] = isset($data['update_time']) ? $data['update_time'] : null;
        $this->container['closed_pnl'] = isset($data['closed_pnl']) ? $data['closed_pnl'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets user_id
     *
     * @return string|null
     */
    public function getUserId()
    {
        return $this->container['user_id'];
    }

    /**
     * Sets user_id
     *
     * @param string|null $user_id User ID
     *
     * @return $this
     */
    public function setUserId($user_id)
    {
        $this->container['user_id'] = $user_id;

        return $this;
    }

    /**
     * Gets position_id
     *
     * @return string|null
     */
    public function getPositionId()
    {
        return $this->container['position_id'];
    }

    /**
     * Sets position_id
     *
     * @param string|null $position_id Position ID
     *
     * @return $this
     */
    public function setPositionId($position_id)
    {
        $this->container['position_id'] = $position_id;

        return $this;
    }

    /**
     * Gets symbol
     *
     * @return string|null
     */
    public function getSymbol()
    {
        return $this->container['symbol'];
    }

    /**
     * Sets symbol
     *
     * @param string|null $symbol Currency pair
     *
     * @return $this
     */
    public function setSymbol($symbol)
    {
        $this->container['symbol'] = $symbol;

        return $this;
    }

    /**
     * Gets position_side
     *
     * @return string|null
     */
    public function getPositionSide()
    {
        return $this->container['position_side'];
    }

    /**
     * Sets position_side
     *
     * @param string|null $position_side Position Direction
     *
     * @return $this
     */
    public function setPositionSide($position_side)
    {
        $this->container['position_side'] = $position_side;

        return $this;
    }

    /**
     * Gets initial_margin
     *
     * @return string|null
     */
    public function getInitialMargin()
    {
        return $this->container['initial_margin'];
    }

    /**
     * Sets initial_margin
     *
     * @param string|null $initial_margin Initial Margin
     *
     * @return $this
     */
    public function setInitialMargin($initial_margin)
    {
        $this->container['initial_margin'] = $initial_margin;

        return $this;
    }

    /**
     * Gets maintenance_margin
     *
     * @return string|null
     */
    public function getMaintenanceMargin()
    {
        return $this->container['maintenance_margin'];
    }

    /**
     * Sets maintenance_margin
     *
     * @param string|null $maintenance_margin Maintenance margin
     *
     * @return $this
     */
    public function setMaintenanceMargin($maintenance_margin)
    {
        $this->container['maintenance_margin'] = $maintenance_margin;

        return $this;
    }

    /**
     * Gets position_qty
     *
     * @return string|null
     */
    public function getPositionQty()
    {
        return $this->container['position_qty'];
    }

    /**
     * Sets position_qty
     *
     * @param string|null $position_qty Position Quantity
     *
     * @return $this
     */
    public function setPositionQty($position_qty)
    {
        $this->container['position_qty'] = $position_qty;

        return $this;
    }

    /**
     * Gets position_value
     *
     * @return string|null
     */
    public function getPositionValue()
    {
        return $this->container['position_value'];
    }

    /**
     * Sets position_value
     *
     * @param string|null $position_value Position Value
     *
     * @return $this
     */
    public function setPositionValue($position_value)
    {
        $this->container['position_value'] = $position_value;

        return $this;
    }

    /**
     * Gets upnl
     *
     * @return string|null
     */
    public function getUpnl()
    {
        return $this->container['upnl'];
    }

    /**
     * Sets upnl
     *
     * @param string|null $upnl Unrealized P&L
     *
     * @return $this
     */
    public function setUpnl($upnl)
    {
        $this->container['upnl'] = $upnl;

        return $this;
    }

    /**
     * Gets upnl_rate
     *
     * @return string|null
     */
    public function getUpnlRate()
    {
        return $this->container['upnl_rate'];
    }

    /**
     * Sets upnl_rate
     *
     * @param string|null $upnl_rate Unrealized P&L Ratio
     *
     * @return $this
     */
    public function setUpnlRate($upnl_rate)
    {
        $this->container['upnl_rate'] = $upnl_rate;

        return $this;
    }

    /**
     * Gets entry_price
     *
     * @return string|null
     */
    public function getEntryPrice()
    {
        return $this->container['entry_price'];
    }

    /**
     * Sets entry_price
     *
     * @param string|null $entry_price Position Average Entry Price
     *
     * @return $this
     */
    public function setEntryPrice($entry_price)
    {
        $this->container['entry_price'] = $entry_price;

        return $this;
    }

    /**
     * Gets mark_price
     *
     * @return string|null
     */
    public function getMarkPrice()
    {
        return $this->container['mark_price'];
    }

    /**
     * Sets mark_price
     *
     * @param string|null $mark_price Mark price
     *
     * @return $this
     */
    public function setMarkPrice($mark_price)
    {
        $this->container['mark_price'] = $mark_price;

        return $this;
    }

    /**
     * Gets leverage
     *
     * @return string|null
     */
    public function getLeverage()
    {
        return $this->container['leverage'];
    }

    /**
     * Sets leverage
     *
     * @param string|null $leverage Position Leverage
     *
     * @return $this
     */
    public function setLeverage($leverage)
    {
        $this->container['leverage'] = $leverage;

        return $this;
    }

    /**
     * Gets max_leverage
     *
     * @return string|null
     */
    public function getMaxLeverage()
    {
        return $this->container['max_leverage'];
    }

    /**
     * Sets max_leverage
     *
     * @param string|null $max_leverage Maximum leverage
     *
     * @return $this
     */
    public function setMaxLeverage($max_leverage)
    {
        $this->container['max_leverage'] = $max_leverage;

        return $this;
    }

    /**
     * Gets risk_limit
     *
     * @return string|null
     */
    public function getRiskLimit()
    {
        return $this->container['risk_limit'];
    }

    /**
     * Sets risk_limit
     *
     * @param string|null $risk_limit Position risk limit
     *
     * @return $this
     */
    public function setRiskLimit($risk_limit)
    {
        $this->container['risk_limit'] = $risk_limit;

        return $this;
    }

    /**
     * Gets fee
     *
     * @return string|null
     */
    public function getFee()
    {
        return $this->container['fee'];
    }

    /**
     * Sets fee
     *
     * @param string|null $fee Position Fee
     *
     * @return $this
     */
    public function setFee($fee)
    {
        $this->container['fee'] = $fee;

        return $this;
    }

    /**
     * Gets funding_fee
     *
     * @return string|null
     */
    public function getFundingFee()
    {
        return $this->container['funding_fee'];
    }

    /**
     * Sets funding_fee
     *
     * @param string|null $funding_fee Position Funding Fee
     *
     * @return $this
     */
    public function setFundingFee($funding_fee)
    {
        $this->container['funding_fee'] = $funding_fee;

        return $this;
    }

    /**
     * Gets funding_time
     *
     * @return string|null
     */
    public function getFundingTime()
    {
        return $this->container['funding_time'];
    }

    /**
     * Sets funding_time
     *
     * @param string|null $funding_time Position funding fee collection time (0 indicates it has not been collected yet)
     *
     * @return $this
     */
    public function setFundingTime($funding_time)
    {
        $this->container['funding_time'] = $funding_time;

        return $this;
    }

    /**
     * Gets create_time
     *
     * @return string|null
     */
    public function getCreateTime()
    {
        return $this->container['create_time'];
    }

    /**
     * Sets create_time
     *
     * @param string|null $create_time Position Creation Time
     *
     * @return $this
     */
    public function setCreateTime($create_time)
    {
        $this->container['create_time'] = $create_time;

        return $this;
    }

    /**
     * Gets update_time
     *
     * @return string|null
     */
    public function getUpdateTime()
    {
        return $this->container['update_time'];
    }

    /**
     * Sets update_time
     *
     * @param string|null $update_time Position Update Time
     *
     * @return $this
     */
    public function setUpdateTime($update_time)
    {
        $this->container['update_time'] = $update_time;

        return $this;
    }

    /**
     * Gets closed_pnl
     *
     * @return string|null
     */
    public function getClosedPnl()
    {
        return $this->container['closed_pnl'];
    }

    /**
     * Sets closed_pnl
     *
     * @param string|null $closed_pnl Realized PnL
     *
     * @return $this
     */
    public function setClosedPnl($closed_pnl)
    {
        $this->container['closed_pnl'] = $closed_pnl;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


