<?php
/**
 * OtcBankCreateMultipartRequest
 *
 * PHP version 7
 *
 * @category Class
 * @package  GateApi
 * @author   Gate
 * @link     https://www.gate.com
 */

/**
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: https://openapi-generator.tech
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */

namespace GateApi\Model;

use \ArrayAccess;
use \GateApi\ObjectSerializer;

/**
 * OtcBankCreateMultipartRequest Class Doc Comment
 *
 * @category Class
 * @description Inner create-bank-card &#x60;multipart/form-data&#x60;. Account-opening proof file (choose one):  - **Pre-upload**: &#x60;documentation_file_key&#x60; + &#x60;file_type&#x60; (call &#x60;POST /otc/upload/pre_upload&#x60; first, &#x60;scene&#x3D;bank&#x60;); - **Multipart direct upload**: &#x60;documentation_file&#x60; file field.
 * @package  GateApi
 * @author   Gate
 * @link     https://www.gate.com
 */
class OtcBankCreateMultipartRequest implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'OtcBankCreateMultipartRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'bank_account_name' => 'string',
        'bank_name' => 'string',
        'bank_country' => 'string',
        'bank_address' => 'string',
        'iban' => 'string',
        'swift' => 'string',
        'remittance_line_number' => 'string',
        'agent_bank_name' => 'string',
        'agent_bank_swift' => 'string',
        'documentation_file' => 'string',
        'documentation_file_key' => 'string',
        'file_type' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPIFormats = [
        'bank_account_name' => null,
        'bank_name' => null,
        'bank_country' => null,
        'bank_address' => null,
        'iban' => null,
        'swift' => null,
        'remittance_line_number' => null,
        'agent_bank_name' => null,
        'agent_bank_swift' => null,
        'documentation_file' => null,
        'documentation_file_key' => null,
        'file_type' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'bank_account_name' => 'bank_account_name',
        'bank_name' => 'bank_name',
        'bank_country' => 'bank_country',
        'bank_address' => 'bank_address',
        'iban' => 'iban',
        'swift' => 'swift',
        'remittance_line_number' => 'remittance_line_number',
        'agent_bank_name' => 'agent_bank_name',
        'agent_bank_swift' => 'agent_bank_swift',
        'documentation_file' => 'documentation_file',
        'documentation_file_key' => 'documentation_file_key',
        'file_type' => 'file_type'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'bank_account_name' => 'setBankAccountName',
        'bank_name' => 'setBankName',
        'bank_country' => 'setBankCountry',
        'bank_address' => 'setBankAddress',
        'iban' => 'setIban',
        'swift' => 'setSwift',
        'remittance_line_number' => 'setRemittanceLineNumber',
        'agent_bank_name' => 'setAgentBankName',
        'agent_bank_swift' => 'setAgentBankSwift',
        'documentation_file' => 'setDocumentationFile',
        'documentation_file_key' => 'setDocumentationFileKey',
        'file_type' => 'setFileType'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'bank_account_name' => 'getBankAccountName',
        'bank_name' => 'getBankName',
        'bank_country' => 'getBankCountry',
        'bank_address' => 'getBankAddress',
        'iban' => 'getIban',
        'swift' => 'getSwift',
        'remittance_line_number' => 'getRemittanceLineNumber',
        'agent_bank_name' => 'getAgentBankName',
        'agent_bank_swift' => 'getAgentBankSwift',
        'documentation_file' => 'getDocumentationFile',
        'documentation_file_key' => 'getDocumentationFileKey',
        'file_type' => 'getFileType'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['bank_account_name'] = isset($data['bank_account_name']) ? $data['bank_account_name'] : null;
        $this->container['bank_name'] = isset($data['bank_name']) ? $data['bank_name'] : null;
        $this->container['bank_country'] = isset($data['bank_country']) ? $data['bank_country'] : null;
        $this->container['bank_address'] = isset($data['bank_address']) ? $data['bank_address'] : null;
        $this->container['iban'] = isset($data['iban']) ? $data['iban'] : null;
        $this->container['swift'] = isset($data['swift']) ? $data['swift'] : null;
        $this->container['remittance_line_number'] = isset($data['remittance_line_number']) ? $data['remittance_line_number'] : null;
        $this->container['agent_bank_name'] = isset($data['agent_bank_name']) ? $data['agent_bank_name'] : null;
        $this->container['agent_bank_swift'] = isset($data['agent_bank_swift']) ? $data['agent_bank_swift'] : null;
        $this->container['documentation_file'] = isset($data['documentation_file']) ? $data['documentation_file'] : null;
        $this->container['documentation_file_key'] = isset($data['documentation_file_key']) ? $data['documentation_file_key'] : null;
        $this->container['file_type'] = isset($data['file_type']) ? $data['file_type'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['bank_account_name'] === null) {
            $invalidProperties[] = "'bank_account_name' can't be null";
        }
        if ($this->container['bank_name'] === null) {
            $invalidProperties[] = "'bank_name' can't be null";
        }
        if ($this->container['bank_country'] === null) {
            $invalidProperties[] = "'bank_country' can't be null";
        }
        if ($this->container['bank_address'] === null) {
            $invalidProperties[] = "'bank_address' can't be null";
        }
        if ($this->container['iban'] === null) {
            $invalidProperties[] = "'iban' can't be null";
        }
        if ($this->container['swift'] === null) {
            $invalidProperties[] = "'swift' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets bank_account_name
     *
     * @return string
     */
    public function getBankAccountName()
    {
        return $this->container['bank_account_name'];
    }

    /**
     * Sets bank_account_name
     *
     * @param string $bank_account_name bank_account_name
     *
     * @return $this
     */
    public function setBankAccountName($bank_account_name)
    {
        $this->container['bank_account_name'] = $bank_account_name;

        return $this;
    }

    /**
     * Gets bank_name
     *
     * @return string
     */
    public function getBankName()
    {
        return $this->container['bank_name'];
    }

    /**
     * Sets bank_name
     *
     * @param string $bank_name bank_name
     *
     * @return $this
     */
    public function setBankName($bank_name)
    {
        $this->container['bank_name'] = $bank_name;

        return $this;
    }

    /**
     * Gets bank_country
     *
     * @return string
     */
    public function getBankCountry()
    {
        return $this->container['bank_country'];
    }

    /**
     * Sets bank_country
     *
     * @param string $bank_country bank_country
     *
     * @return $this
     */
    public function setBankCountry($bank_country)
    {
        $this->container['bank_country'] = $bank_country;

        return $this;
    }

    /**
     * Gets bank_address
     *
     * @return string
     */
    public function getBankAddress()
    {
        return $this->container['bank_address'];
    }

    /**
     * Sets bank_address
     *
     * @param string $bank_address bank_address
     *
     * @return $this
     */
    public function setBankAddress($bank_address)
    {
        $this->container['bank_address'] = $bank_address;

        return $this;
    }

    /**
     * Gets iban
     *
     * @return string
     */
    public function getIban()
    {
        return $this->container['iban'];
    }

    /**
     * Sets iban
     *
     * @param string $iban iban
     *
     * @return $this
     */
    public function setIban($iban)
    {
        $this->container['iban'] = $iban;

        return $this;
    }

    /**
     * Gets swift
     *
     * @return string
     */
    public function getSwift()
    {
        return $this->container['swift'];
    }

    /**
     * Sets swift
     *
     * @param string $swift swift
     *
     * @return $this
     */
    public function setSwift($swift)
    {
        $this->container['swift'] = $swift;

        return $this;
    }

    /**
     * Gets remittance_line_number
     *
     * @return string|null
     */
    public function getRemittanceLineNumber()
    {
        return $this->container['remittance_line_number'];
    }

    /**
     * Sets remittance_line_number
     *
     * @param string|null $remittance_line_number remittance_line_number
     *
     * @return $this
     */
    public function setRemittanceLineNumber($remittance_line_number)
    {
        $this->container['remittance_line_number'] = $remittance_line_number;

        return $this;
    }

    /**
     * Gets agent_bank_name
     *
     * @return string|null
     */
    public function getAgentBankName()
    {
        return $this->container['agent_bank_name'];
    }

    /**
     * Sets agent_bank_name
     *
     * @param string|null $agent_bank_name agent_bank_name
     *
     * @return $this
     */
    public function setAgentBankName($agent_bank_name)
    {
        $this->container['agent_bank_name'] = $agent_bank_name;

        return $this;
    }

    /**
     * Gets agent_bank_swift
     *
     * @return string|null
     */
    public function getAgentBankSwift()
    {
        return $this->container['agent_bank_swift'];
    }

    /**
     * Sets agent_bank_swift
     *
     * @param string|null $agent_bank_swift agent_bank_swift
     *
     * @return $this
     */
    public function setAgentBankSwift($agent_bank_swift)
    {
        $this->container['agent_bank_swift'] = $agent_bank_swift;

        return $this;
    }

    /**
     * Gets documentation_file
     *
     * @return string|null
     */
    public function getDocumentationFile()
    {
        return $this->container['documentation_file'];
    }

    /**
     * Sets documentation_file
     *
     * @param string|null $documentation_file Multipart direct upload; mutually exclusive with documentation_file_key
     *
     * @return $this
     */
    public function setDocumentationFile($documentation_file)
    {
        $this->container['documentation_file'] = $documentation_file;

        return $this;
    }

    /**
     * Gets documentation_file_key
     *
     * @return string|null
     */
    public function getDocumentationFileKey()
    {
        return $this->container['documentation_file_key'];
    }

    /**
     * Sets documentation_file_key
     *
     * @param string|null $documentation_file_key Pre-upload mode; file_key returned by pre_upload (plaintext or base64 accepted)
     *
     * @return $this
     */
    public function setDocumentationFileKey($documentation_file_key)
    {
        $this->container['documentation_file_key'] = $documentation_file_key;

        return $this;
    }

    /**
     * Gets file_type
     *
     * @return string|null
     */
    public function getFileType()
    {
        return $this->container['file_type'];
    }

    /**
     * Sets file_type
     *
     * @param string|null $file_type Required when using documentation_file_key; plaintext MIME or its base64
     *
     * @return $this
     */
    public function setFileType($file_type)
    {
        $this->container['file_type'] = $file_type;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


