<?php
/**
 * OtcOrderDetail
 *
 * PHP version 7
 *
 * @category Class
 * @package  GateApi
 * @author   Gate
 * @link     https://www.gate.com
 */

/**
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: https://openapi-generator.tech
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */

namespace GateApi\Model;

use \ArrayAccess;
use \GateApi\ObjectSerializer;

/**
 * OtcOrderDetail Class Doc Comment
 *
 * @category Class
 * @package  GateApi
 * @author   Gate
 * @link     https://www.gate.com
 */
class OtcOrderDetail implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'OtcOrderDetail';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'order_id' => 'string',
        'uid' => 'string',
        'type' => 'string',
        'fiat_currency' => 'string',
        'fiat_amount' => 'string',
        'crypto_currency' => 'string',
        'crypto_amount' => 'string',
        'rate' => 'string',
        'bank_account_name' => 'string',
        'bank_name' => 'string',
        'bank_country' => 'string',
        'bank_address' => 'string',
        'bank_account_number_iban' => 'string',
        'swift_code' => 'string',
        'intermediate_bank_name' => 'string',
        'intermediary_bank_swift_code' => 'string',
        'gate_bank_account_name' => 'string',
        'gate_bank_name' => 'string',
        'gate_bank_country' => 'string',
        'gate_bank_address' => 'string',
        'gate_bank_account_number_iban' => 'string',
        'gate_swift_code' => 'string',
        'gate_intermediary_bank_name' => 'string',
        'gate_intermediary_bank_swift_code' => 'string',
        'gate_transfer_remark' => 'string',
        'gate_reference_code' => 'string',
        'status' => 'string',
        'create_time' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPIFormats = [
        'order_id' => null,
        'uid' => null,
        'type' => null,
        'fiat_currency' => null,
        'fiat_amount' => null,
        'crypto_currency' => null,
        'crypto_amount' => null,
        'rate' => null,
        'bank_account_name' => null,
        'bank_name' => null,
        'bank_country' => null,
        'bank_address' => null,
        'bank_account_number_iban' => null,
        'swift_code' => null,
        'intermediate_bank_name' => null,
        'intermediary_bank_swift_code' => null,
        'gate_bank_account_name' => null,
        'gate_bank_name' => null,
        'gate_bank_country' => null,
        'gate_bank_address' => null,
        'gate_bank_account_number_iban' => null,
        'gate_swift_code' => null,
        'gate_intermediary_bank_name' => null,
        'gate_intermediary_bank_swift_code' => null,
        'gate_transfer_remark' => null,
        'gate_reference_code' => null,
        'status' => null,
        'create_time' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'order_id' => 'order_id',
        'uid' => 'uid',
        'type' => 'type',
        'fiat_currency' => 'fiat_currency',
        'fiat_amount' => 'fiat_amount',
        'crypto_currency' => 'crypto_currency',
        'crypto_amount' => 'crypto_amount',
        'rate' => 'rate',
        'bank_account_name' => 'bank_account_name',
        'bank_name' => 'bank_name',
        'bank_country' => 'bank_country',
        'bank_address' => 'bank_address',
        'bank_account_number_iban' => 'bank_account_number_iban',
        'swift_code' => 'swift_code',
        'intermediate_bank_name' => 'intermediate_bank_name',
        'intermediary_bank_swift_code' => 'intermediary_bank_swift_code',
        'gate_bank_account_name' => 'gate_bank_account_name',
        'gate_bank_name' => 'gate_bank_name',
        'gate_bank_country' => 'gate_bank_country',
        'gate_bank_address' => 'gate_bank_address',
        'gate_bank_account_number_iban' => 'gate_bank_account_number_iban',
        'gate_swift_code' => 'gate_swift_code',
        'gate_intermediary_bank_name' => 'gate_intermediary_bank_name',
        'gate_intermediary_bank_swift_code' => 'gate_intermediary_bank_swift_code',
        'gate_transfer_remark' => 'gate_transfer_remark',
        'gate_reference_code' => 'gate_reference_code',
        'status' => 'status',
        'create_time' => 'create_time'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'order_id' => 'setOrderId',
        'uid' => 'setUid',
        'type' => 'setType',
        'fiat_currency' => 'setFiatCurrency',
        'fiat_amount' => 'setFiatAmount',
        'crypto_currency' => 'setCryptoCurrency',
        'crypto_amount' => 'setCryptoAmount',
        'rate' => 'setRate',
        'bank_account_name' => 'setBankAccountName',
        'bank_name' => 'setBankName',
        'bank_country' => 'setBankCountry',
        'bank_address' => 'setBankAddress',
        'bank_account_number_iban' => 'setBankAccountNumberIban',
        'swift_code' => 'setSwiftCode',
        'intermediate_bank_name' => 'setIntermediateBankName',
        'intermediary_bank_swift_code' => 'setIntermediaryBankSwiftCode',
        'gate_bank_account_name' => 'setGateBankAccountName',
        'gate_bank_name' => 'setGateBankName',
        'gate_bank_country' => 'setGateBankCountry',
        'gate_bank_address' => 'setGateBankAddress',
        'gate_bank_account_number_iban' => 'setGateBankAccountNumberIban',
        'gate_swift_code' => 'setGateSwiftCode',
        'gate_intermediary_bank_name' => 'setGateIntermediaryBankName',
        'gate_intermediary_bank_swift_code' => 'setGateIntermediaryBankSwiftCode',
        'gate_transfer_remark' => 'setGateTransferRemark',
        'gate_reference_code' => 'setGateReferenceCode',
        'status' => 'setStatus',
        'create_time' => 'setCreateTime'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'order_id' => 'getOrderId',
        'uid' => 'getUid',
        'type' => 'getType',
        'fiat_currency' => 'getFiatCurrency',
        'fiat_amount' => 'getFiatAmount',
        'crypto_currency' => 'getCryptoCurrency',
        'crypto_amount' => 'getCryptoAmount',
        'rate' => 'getRate',
        'bank_account_name' => 'getBankAccountName',
        'bank_name' => 'getBankName',
        'bank_country' => 'getBankCountry',
        'bank_address' => 'getBankAddress',
        'bank_account_number_iban' => 'getBankAccountNumberIban',
        'swift_code' => 'getSwiftCode',
        'intermediate_bank_name' => 'getIntermediateBankName',
        'intermediary_bank_swift_code' => 'getIntermediaryBankSwiftCode',
        'gate_bank_account_name' => 'getGateBankAccountName',
        'gate_bank_name' => 'getGateBankName',
        'gate_bank_country' => 'getGateBankCountry',
        'gate_bank_address' => 'getGateBankAddress',
        'gate_bank_account_number_iban' => 'getGateBankAccountNumberIban',
        'gate_swift_code' => 'getGateSwiftCode',
        'gate_intermediary_bank_name' => 'getGateIntermediaryBankName',
        'gate_intermediary_bank_swift_code' => 'getGateIntermediaryBankSwiftCode',
        'gate_transfer_remark' => 'getGateTransferRemark',
        'gate_reference_code' => 'getGateReferenceCode',
        'status' => 'getStatus',
        'create_time' => 'getCreateTime'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['order_id'] = isset($data['order_id']) ? $data['order_id'] : null;
        $this->container['uid'] = isset($data['uid']) ? $data['uid'] : null;
        $this->container['type'] = isset($data['type']) ? $data['type'] : null;
        $this->container['fiat_currency'] = isset($data['fiat_currency']) ? $data['fiat_currency'] : null;
        $this->container['fiat_amount'] = isset($data['fiat_amount']) ? $data['fiat_amount'] : null;
        $this->container['crypto_currency'] = isset($data['crypto_currency']) ? $data['crypto_currency'] : null;
        $this->container['crypto_amount'] = isset($data['crypto_amount']) ? $data['crypto_amount'] : null;
        $this->container['rate'] = isset($data['rate']) ? $data['rate'] : null;
        $this->container['bank_account_name'] = isset($data['bank_account_name']) ? $data['bank_account_name'] : null;
        $this->container['bank_name'] = isset($data['bank_name']) ? $data['bank_name'] : null;
        $this->container['bank_country'] = isset($data['bank_country']) ? $data['bank_country'] : null;
        $this->container['bank_address'] = isset($data['bank_address']) ? $data['bank_address'] : null;
        $this->container['bank_account_number_iban'] = isset($data['bank_account_number_iban']) ? $data['bank_account_number_iban'] : null;
        $this->container['swift_code'] = isset($data['swift_code']) ? $data['swift_code'] : null;
        $this->container['intermediate_bank_name'] = isset($data['intermediate_bank_name']) ? $data['intermediate_bank_name'] : null;
        $this->container['intermediary_bank_swift_code'] = isset($data['intermediary_bank_swift_code']) ? $data['intermediary_bank_swift_code'] : null;
        $this->container['gate_bank_account_name'] = isset($data['gate_bank_account_name']) ? $data['gate_bank_account_name'] : null;
        $this->container['gate_bank_name'] = isset($data['gate_bank_name']) ? $data['gate_bank_name'] : null;
        $this->container['gate_bank_country'] = isset($data['gate_bank_country']) ? $data['gate_bank_country'] : null;
        $this->container['gate_bank_address'] = isset($data['gate_bank_address']) ? $data['gate_bank_address'] : null;
        $this->container['gate_bank_account_number_iban'] = isset($data['gate_bank_account_number_iban']) ? $data['gate_bank_account_number_iban'] : null;
        $this->container['gate_swift_code'] = isset($data['gate_swift_code']) ? $data['gate_swift_code'] : null;
        $this->container['gate_intermediary_bank_name'] = isset($data['gate_intermediary_bank_name']) ? $data['gate_intermediary_bank_name'] : null;
        $this->container['gate_intermediary_bank_swift_code'] = isset($data['gate_intermediary_bank_swift_code']) ? $data['gate_intermediary_bank_swift_code'] : null;
        $this->container['gate_transfer_remark'] = isset($data['gate_transfer_remark']) ? $data['gate_transfer_remark'] : null;
        $this->container['gate_reference_code'] = isset($data['gate_reference_code']) ? $data['gate_reference_code'] : null;
        $this->container['status'] = isset($data['status']) ? $data['status'] : null;
        $this->container['create_time'] = isset($data['create_time']) ? $data['create_time'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['order_id'] === null) {
            $invalidProperties[] = "'order_id' can't be null";
        }
        if ($this->container['uid'] === null) {
            $invalidProperties[] = "'uid' can't be null";
        }
        if ($this->container['type'] === null) {
            $invalidProperties[] = "'type' can't be null";
        }
        if ($this->container['fiat_currency'] === null) {
            $invalidProperties[] = "'fiat_currency' can't be null";
        }
        if ($this->container['fiat_amount'] === null) {
            $invalidProperties[] = "'fiat_amount' can't be null";
        }
        if ($this->container['crypto_currency'] === null) {
            $invalidProperties[] = "'crypto_currency' can't be null";
        }
        if ($this->container['crypto_amount'] === null) {
            $invalidProperties[] = "'crypto_amount' can't be null";
        }
        if ($this->container['rate'] === null) {
            $invalidProperties[] = "'rate' can't be null";
        }
        if ($this->container['status'] === null) {
            $invalidProperties[] = "'status' can't be null";
        }
        if ($this->container['create_time'] === null) {
            $invalidProperties[] = "'create_time' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets order_id
     *
     * @return string
     */
    public function getOrderId()
    {
        return $this->container['order_id'];
    }

    /**
     * Sets order_id
     *
     * @param string $order_id Order ID
     *
     * @return $this
     */
    public function setOrderId($order_id)
    {
        $this->container['order_id'] = $order_id;

        return $this;
    }

    /**
     * Gets uid
     *
     * @return string
     */
    public function getUid()
    {
        return $this->container['uid'];
    }

    /**
     * Sets uid
     *
     * @param string $uid User ID
     *
     * @return $this
     */
    public function setUid($uid)
    {
        $this->container['uid'] = $uid;

        return $this;
    }

    /**
     * Gets type
     *
     * @return string
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param string $type Order Type
     *
     * @return $this
     */
    public function setType($type)
    {
        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets fiat_currency
     *
     * @return string
     */
    public function getFiatCurrency()
    {
        return $this->container['fiat_currency'];
    }

    /**
     * Sets fiat_currency
     *
     * @param string $fiat_currency Fiat currency
     *
     * @return $this
     */
    public function setFiatCurrency($fiat_currency)
    {
        $this->container['fiat_currency'] = $fiat_currency;

        return $this;
    }

    /**
     * Gets fiat_amount
     *
     * @return string
     */
    public function getFiatAmount()
    {
        return $this->container['fiat_amount'];
    }

    /**
     * Sets fiat_amount
     *
     * @param string $fiat_amount Fiat amount
     *
     * @return $this
     */
    public function setFiatAmount($fiat_amount)
    {
        $this->container['fiat_amount'] = $fiat_amount;

        return $this;
    }

    /**
     * Gets crypto_currency
     *
     * @return string
     */
    public function getCryptoCurrency()
    {
        return $this->container['crypto_currency'];
    }

    /**
     * Sets crypto_currency
     *
     * @param string $crypto_currency Digital currency
     *
     * @return $this
     */
    public function setCryptoCurrency($crypto_currency)
    {
        $this->container['crypto_currency'] = $crypto_currency;

        return $this;
    }

    /**
     * Gets crypto_amount
     *
     * @return string
     */
    public function getCryptoAmount()
    {
        return $this->container['crypto_amount'];
    }

    /**
     * Sets crypto_amount
     *
     * @param string $crypto_amount Cryptocurrency amount
     *
     * @return $this
     */
    public function setCryptoAmount($crypto_amount)
    {
        $this->container['crypto_amount'] = $crypto_amount;

        return $this;
    }

    /**
     * Gets rate
     *
     * @return string
     */
    public function getRate()
    {
        return $this->container['rate'];
    }

    /**
     * Sets rate
     *
     * @param string $rate Exchange rate
     *
     * @return $this
     */
    public function setRate($rate)
    {
        $this->container['rate'] = $rate;

        return $this;
    }

    /**
     * Gets bank_account_name
     *
     * @return string|null
     */
    public function getBankAccountName()
    {
        return $this->container['bank_account_name'];
    }

    /**
     * Sets bank_account_name
     *
     * @param string|null $bank_account_name User payment/receiving name
     *
     * @return $this
     */
    public function setBankAccountName($bank_account_name)
    {
        $this->container['bank_account_name'] = $bank_account_name;

        return $this;
    }

    /**
     * Gets bank_name
     *
     * @return string|null
     */
    public function getBankName()
    {
        return $this->container['bank_name'];
    }

    /**
     * Sets bank_name
     *
     * @param string|null $bank_name User payment/receiving bank name
     *
     * @return $this
     */
    public function setBankName($bank_name)
    {
        $this->container['bank_name'] = $bank_name;

        return $this;
    }

    /**
     * Gets bank_country
     *
     * @return string|null
     */
    public function getBankCountry()
    {
        return $this->container['bank_country'];
    }

    /**
     * Sets bank_country
     *
     * @param string|null $bank_country User payment/receiving bank country
     *
     * @return $this
     */
    public function setBankCountry($bank_country)
    {
        $this->container['bank_country'] = $bank_country;

        return $this;
    }

    /**
     * Gets bank_address
     *
     * @return string|null
     */
    public function getBankAddress()
    {
        return $this->container['bank_address'];
    }

    /**
     * Sets bank_address
     *
     * @param string|null $bank_address User payment/receiving bank address
     *
     * @return $this
     */
    public function setBankAddress($bank_address)
    {
        $this->container['bank_address'] = $bank_address;

        return $this;
    }

    /**
     * Gets bank_account_number_iban
     *
     * @return string|null
     */
    public function getBankAccountNumberIban()
    {
        return $this->container['bank_account_number_iban'];
    }

    /**
     * Sets bank_account_number_iban
     *
     * @param string|null $bank_account_number_iban User payment/receiving bank account number/IBAN
     *
     * @return $this
     */
    public function setBankAccountNumberIban($bank_account_number_iban)
    {
        $this->container['bank_account_number_iban'] = $bank_account_number_iban;

        return $this;
    }

    /**
     * Gets swift_code
     *
     * @return string|null
     */
    public function getSwiftCode()
    {
        return $this->container['swift_code'];
    }

    /**
     * Sets swift_code
     *
     * @param string|null $swift_code User payment/receiving bank SWIFT code
     *
     * @return $this
     */
    public function setSwiftCode($swift_code)
    {
        $this->container['swift_code'] = $swift_code;

        return $this;
    }

    /**
     * Gets intermediate_bank_name
     *
     * @return string|null
     */
    public function getIntermediateBankName()
    {
        return $this->container['intermediate_bank_name'];
    }

    /**
     * Sets intermediate_bank_name
     *
     * @param string|null $intermediate_bank_name User payment/receiving intermediary bank name
     *
     * @return $this
     */
    public function setIntermediateBankName($intermediate_bank_name)
    {
        $this->container['intermediate_bank_name'] = $intermediate_bank_name;

        return $this;
    }

    /**
     * Gets intermediary_bank_swift_code
     *
     * @return string|null
     */
    public function getIntermediaryBankSwiftCode()
    {
        return $this->container['intermediary_bank_swift_code'];
    }

    /**
     * Sets intermediary_bank_swift_code
     *
     * @param string|null $intermediary_bank_swift_code User payment/receiving intermediary bank SWIFT code
     *
     * @return $this
     */
    public function setIntermediaryBankSwiftCode($intermediary_bank_swift_code)
    {
        $this->container['intermediary_bank_swift_code'] = $intermediary_bank_swift_code;

        return $this;
    }

    /**
     * Gets gate_bank_account_name
     *
     * @return string|null
     */
    public function getGateBankAccountName()
    {
        return $this->container['gate_bank_account_name'];
    }

    /**
     * Sets gate_bank_account_name
     *
     * @param string|null $gate_bank_account_name Gate beneficiary name, shown for BUY only
     *
     * @return $this
     */
    public function setGateBankAccountName($gate_bank_account_name)
    {
        $this->container['gate_bank_account_name'] = $gate_bank_account_name;

        return $this;
    }

    /**
     * Gets gate_bank_name
     *
     * @return string|null
     */
    public function getGateBankName()
    {
        return $this->container['gate_bank_name'];
    }

    /**
     * Sets gate_bank_name
     *
     * @param string|null $gate_bank_name Gate beneficiary bank name, shown for BUY only
     *
     * @return $this
     */
    public function setGateBankName($gate_bank_name)
    {
        $this->container['gate_bank_name'] = $gate_bank_name;

        return $this;
    }

    /**
     * Gets gate_bank_country
     *
     * @return string|null
     */
    public function getGateBankCountry()
    {
        return $this->container['gate_bank_country'];
    }

    /**
     * Sets gate_bank_country
     *
     * @param string|null $gate_bank_country Gate beneficiary bank country, shown for BUY only
     *
     * @return $this
     */
    public function setGateBankCountry($gate_bank_country)
    {
        $this->container['gate_bank_country'] = $gate_bank_country;

        return $this;
    }

    /**
     * Gets gate_bank_address
     *
     * @return string|null
     */
    public function getGateBankAddress()
    {
        return $this->container['gate_bank_address'];
    }

    /**
     * Sets gate_bank_address
     *
     * @param string|null $gate_bank_address Gate beneficiary bank address, shown for BUY only
     *
     * @return $this
     */
    public function setGateBankAddress($gate_bank_address)
    {
        $this->container['gate_bank_address'] = $gate_bank_address;

        return $this;
    }

    /**
     * Gets gate_bank_account_number_iban
     *
     * @return string|null
     */
    public function getGateBankAccountNumberIban()
    {
        return $this->container['gate_bank_account_number_iban'];
    }

    /**
     * Sets gate_bank_account_number_iban
     *
     * @param string|null $gate_bank_account_number_iban Gate beneficiary bank account number/IBAN, shown for BUY only
     *
     * @return $this
     */
    public function setGateBankAccountNumberIban($gate_bank_account_number_iban)
    {
        $this->container['gate_bank_account_number_iban'] = $gate_bank_account_number_iban;

        return $this;
    }

    /**
     * Gets gate_swift_code
     *
     * @return string|null
     */
    public function getGateSwiftCode()
    {
        return $this->container['gate_swift_code'];
    }

    /**
     * Sets gate_swift_code
     *
     * @param string|null $gate_swift_code Gate beneficiary bank SWIFT code, shown for BUY only
     *
     * @return $this
     */
    public function setGateSwiftCode($gate_swift_code)
    {
        $this->container['gate_swift_code'] = $gate_swift_code;

        return $this;
    }

    /**
     * Gets gate_intermediary_bank_name
     *
     * @return string|null
     */
    public function getGateIntermediaryBankName()
    {
        return $this->container['gate_intermediary_bank_name'];
    }

    /**
     * Sets gate_intermediary_bank_name
     *
     * @param string|null $gate_intermediary_bank_name Gate beneficiary intermediary bank name, shown for BUY only
     *
     * @return $this
     */
    public function setGateIntermediaryBankName($gate_intermediary_bank_name)
    {
        $this->container['gate_intermediary_bank_name'] = $gate_intermediary_bank_name;

        return $this;
    }

    /**
     * Gets gate_intermediary_bank_swift_code
     *
     * @return string|null
     */
    public function getGateIntermediaryBankSwiftCode()
    {
        return $this->container['gate_intermediary_bank_swift_code'];
    }

    /**
     * Sets gate_intermediary_bank_swift_code
     *
     * @param string|null $gate_intermediary_bank_swift_code Gate beneficiary intermediary bank SWIFT code, shown for BUY only
     *
     * @return $this
     */
    public function setGateIntermediaryBankSwiftCode($gate_intermediary_bank_swift_code)
    {
        $this->container['gate_intermediary_bank_swift_code'] = $gate_intermediary_bank_swift_code;

        return $this;
    }

    /**
     * Gets gate_transfer_remark
     *
     * @return string|null
     */
    public function getGateTransferRemark()
    {
        return $this->container['gate_transfer_remark'];
    }

    /**
     * Sets gate_transfer_remark
     *
     * @param string|null $gate_transfer_remark Transfer remark (mutually exclusive with `gate_reference_code`; empty when a BUY deposit order has a reference code), shown for BUY only
     *
     * @return $this
     */
    public function setGateTransferRemark($gate_transfer_remark)
    {
        $this->container['gate_transfer_remark'] = $gate_transfer_remark;

        return $this;
    }

    /**
     * Gets gate_reference_code
     *
     * @return string|null
     */
    public function getGateReferenceCode()
    {
        return $this->container['gate_reference_code'];
    }

    /**
     * Sets gate_reference_code
     *
     * @param string|null $gate_reference_code Be sure to include the reference code when making the transfer so that your order can be processed promptly. (Mutually exclusive with `gate_transfer_remark`.)
     *
     * @return $this
     */
    public function setGateReferenceCode($gate_reference_code)
    {
        $this->container['gate_reference_code'] = $gate_reference_code;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string $status Status
     *
     * @return $this
     */
    public function setStatus($status)
    {
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets create_time
     *
     * @return string
     */
    public function getCreateTime()
    {
        return $this->container['create_time'];
    }

    /**
     * Sets create_time
     *
     * @param string $create_time Created time
     *
     * @return $this
     */
    public function setCreateTime($create_time)
    {
        $this->container['create_time'] = $create_time;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


