<?php
/**
 * P2pAdsListItem
 *
 * PHP version 7
 *
 * @category Class
 * @package  GateApi
 * @author   Gate
 * @link     https://www.gate.com
 */

/**
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: https://openapi-generator.tech
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */

namespace GateApi\Model;

use \ArrayAccess;
use \GateApi\ObjectSerializer;

/**
 * P2pAdsListItem Class Doc Comment
 *
 * @category Class
 * @package  GateApi
 * @author   Gate
 * @link     https://www.gate.com
 */
class P2pAdsListItem implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'P2pAdsListItem';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'index' => 'int',
        'asset' => 'string',
        'fiat_unit' => 'string',
        'adv_no' => 'int',
        'price' => 'string',
        'surplus_amount' => 'string',
        'max_single_trans_amount' => 'string',
        'min_single_trans_amount' => 'string',
        'fiat_min_amount' => 'string',
        'fiat_max_amount' => 'string',
        'limit_basis' => 'int',
        'limit_basis_text' => 'string',
        'trade_methods' => '\GateApi\Model\P2pAdsListTradeMethod[]',
        'nick_name' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPIFormats = [
        'index' => null,
        'asset' => null,
        'fiat_unit' => null,
        'adv_no' => null,
        'price' => null,
        'surplus_amount' => null,
        'max_single_trans_amount' => null,
        'min_single_trans_amount' => null,
        'fiat_min_amount' => null,
        'fiat_max_amount' => null,
        'limit_basis' => null,
        'limit_basis_text' => null,
        'trade_methods' => null,
        'nick_name' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'index' => 'index',
        'asset' => 'asset',
        'fiat_unit' => 'fiat_unit',
        'adv_no' => 'adv_no',
        'price' => 'price',
        'surplus_amount' => 'surplus_amount',
        'max_single_trans_amount' => 'max_single_trans_amount',
        'min_single_trans_amount' => 'min_single_trans_amount',
        'fiat_min_amount' => 'fiat_min_amount',
        'fiat_max_amount' => 'fiat_max_amount',
        'limit_basis' => 'limit_basis',
        'limit_basis_text' => 'limit_basis_text',
        'trade_methods' => 'trade_methods',
        'nick_name' => 'nick_name'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'index' => 'setIndex',
        'asset' => 'setAsset',
        'fiat_unit' => 'setFiatUnit',
        'adv_no' => 'setAdvNo',
        'price' => 'setPrice',
        'surplus_amount' => 'setSurplusAmount',
        'max_single_trans_amount' => 'setMaxSingleTransAmount',
        'min_single_trans_amount' => 'setMinSingleTransAmount',
        'fiat_min_amount' => 'setFiatMinAmount',
        'fiat_max_amount' => 'setFiatMaxAmount',
        'limit_basis' => 'setLimitBasis',
        'limit_basis_text' => 'setLimitBasisText',
        'trade_methods' => 'setTradeMethods',
        'nick_name' => 'setNickName'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'index' => 'getIndex',
        'asset' => 'getAsset',
        'fiat_unit' => 'getFiatUnit',
        'adv_no' => 'getAdvNo',
        'price' => 'getPrice',
        'surplus_amount' => 'getSurplusAmount',
        'max_single_trans_amount' => 'getMaxSingleTransAmount',
        'min_single_trans_amount' => 'getMinSingleTransAmount',
        'fiat_min_amount' => 'getFiatMinAmount',
        'fiat_max_amount' => 'getFiatMaxAmount',
        'limit_basis' => 'getLimitBasis',
        'limit_basis_text' => 'getLimitBasisText',
        'trade_methods' => 'getTradeMethods',
        'nick_name' => 'getNickName'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    const LIMIT_BASIS_0 = 0;
    const LIMIT_BASIS_1 = 1;
    const LIMIT_BASIS_TEXT_CRYPTO = 'crypto';
    const LIMIT_BASIS_TEXT_FIAT = 'fiat';
    

    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getLimitBasisAllowableValues()
    {
        return [
            self::LIMIT_BASIS_0,
            self::LIMIT_BASIS_1,
        ];
    }
    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getLimitBasisTextAllowableValues()
    {
        return [
            self::LIMIT_BASIS_TEXT_CRYPTO,
            self::LIMIT_BASIS_TEXT_FIAT,
        ];
    }
    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['index'] = isset($data['index']) ? $data['index'] : null;
        $this->container['asset'] = isset($data['asset']) ? $data['asset'] : null;
        $this->container['fiat_unit'] = isset($data['fiat_unit']) ? $data['fiat_unit'] : null;
        $this->container['adv_no'] = isset($data['adv_no']) ? $data['adv_no'] : null;
        $this->container['price'] = isset($data['price']) ? $data['price'] : null;
        $this->container['surplus_amount'] = isset($data['surplus_amount']) ? $data['surplus_amount'] : null;
        $this->container['max_single_trans_amount'] = isset($data['max_single_trans_amount']) ? $data['max_single_trans_amount'] : null;
        $this->container['min_single_trans_amount'] = isset($data['min_single_trans_amount']) ? $data['min_single_trans_amount'] : null;
        $this->container['fiat_min_amount'] = isset($data['fiat_min_amount']) ? $data['fiat_min_amount'] : null;
        $this->container['fiat_max_amount'] = isset($data['fiat_max_amount']) ? $data['fiat_max_amount'] : null;
        $this->container['limit_basis'] = isset($data['limit_basis']) ? $data['limit_basis'] : null;
        $this->container['limit_basis_text'] = isset($data['limit_basis_text']) ? $data['limit_basis_text'] : null;
        $this->container['trade_methods'] = isset($data['trade_methods']) ? $data['trade_methods'] : null;
        $this->container['nick_name'] = isset($data['nick_name']) ? $data['nick_name'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getLimitBasisAllowableValues();
        if (!is_null($this->container['limit_basis']) && !in_array($this->container['limit_basis'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'limit_basis', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getLimitBasisTextAllowableValues();
        if (!is_null($this->container['limit_basis_text']) && !in_array($this->container['limit_basis_text'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'limit_basis_text', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets index
     *
     * @return int|null
     */
    public function getIndex()
    {
        return $this->container['index'];
    }

    /**
     * Sets index
     *
     * @param int|null $index Serial number
     *
     * @return $this
     */
    public function setIndex($index)
    {
        $this->container['index'] = $index;

        return $this;
    }

    /**
     * Gets asset
     *
     * @return string|null
     */
    public function getAsset()
    {
        return $this->container['asset'];
    }

    /**
     * Sets asset
     *
     * @param string|null $asset Cryptocurrency
     *
     * @return $this
     */
    public function setAsset($asset)
    {
        $this->container['asset'] = $asset;

        return $this;
    }

    /**
     * Gets fiat_unit
     *
     * @return string|null
     */
    public function getFiatUnit()
    {
        return $this->container['fiat_unit'];
    }

    /**
     * Sets fiat_unit
     *
     * @param string|null $fiat_unit Fiat currency
     *
     * @return $this
     */
    public function setFiatUnit($fiat_unit)
    {
        $this->container['fiat_unit'] = $fiat_unit;

        return $this;
    }

    /**
     * Gets adv_no
     *
     * @return int|null
     */
    public function getAdvNo()
    {
        return $this->container['adv_no'];
    }

    /**
     * Sets adv_no
     *
     * @param int|null $adv_no Ad ID
     *
     * @return $this
     */
    public function setAdvNo($adv_no)
    {
        $this->container['adv_no'] = $adv_no;

        return $this;
    }

    /**
     * Gets price
     *
     * @return string|null
     */
    public function getPrice()
    {
        return $this->container['price'];
    }

    /**
     * Sets price
     *
     * @param string|null $price Price
     *
     * @return $this
     */
    public function setPrice($price)
    {
        $this->container['price'] = $price;

        return $this;
    }

    /**
     * Gets surplus_amount
     *
     * @return string|null
     */
    public function getSurplusAmount()
    {
        return $this->container['surplus_amount'];
    }

    /**
     * Sets surplus_amount
     *
     * @param string|null $surplus_amount Remaining tradable crypto quantity
     *
     * @return $this
     */
    public function setSurplusAmount($surplus_amount)
    {
        $this->container['surplus_amount'] = $surplus_amount;

        return $this;
    }

    /**
     * Gets max_single_trans_amount
     *
     * @return string|null
     */
    public function getMaxSingleTransAmount()
    {
        return $this->container['max_single_trans_amount'];
    }

    /**
     * Sets max_single_trans_amount
     *
     * @param string|null $max_single_trans_amount Maximum crypto size per trade.
     *
     * @return $this
     */
    public function setMaxSingleTransAmount($max_single_trans_amount)
    {
        $this->container['max_single_trans_amount'] = $max_single_trans_amount;

        return $this;
    }

    /**
     * Gets min_single_trans_amount
     *
     * @return string|null
     */
    public function getMinSingleTransAmount()
    {
        return $this->container['min_single_trans_amount'];
    }

    /**
     * Sets min_single_trans_amount
     *
     * @param string|null $min_single_trans_amount Minimum crypto size per trade.
     *
     * @return $this
     */
    public function setMinSingleTransAmount($min_single_trans_amount)
    {
        $this->container['min_single_trans_amount'] = $min_single_trans_amount;

        return $this;
    }

    /**
     * Gets fiat_min_amount
     *
     * @return string|null
     */
    public function getFiatMinAmount()
    {
        return $this->container['fiat_min_amount'];
    }

    /**
     * Sets fiat_min_amount
     *
     * @param string|null $fiat_min_amount Minimum fiat amount per order
     *
     * @return $this
     */
    public function setFiatMinAmount($fiat_min_amount)
    {
        $this->container['fiat_min_amount'] = $fiat_min_amount;

        return $this;
    }

    /**
     * Gets fiat_max_amount
     *
     * @return string|null
     */
    public function getFiatMaxAmount()
    {
        return $this->container['fiat_max_amount'];
    }

    /**
     * Sets fiat_max_amount
     *
     * @param string|null $fiat_max_amount Maximum fiat amount per order
     *
     * @return $this
     */
    public function setFiatMaxAmount($fiat_max_amount)
    {
        $this->container['fiat_max_amount'] = $fiat_max_amount;

        return $this;
    }

    /**
     * Gets limit_basis
     *
     * @return int|null
     */
    public function getLimitBasis()
    {
        return $this->container['limit_basis'];
    }

    /**
     * Sets limit_basis
     *
     * @param int|null $limit_basis Trading limit unit. 0: crypto quantity, 1: fiat amount
     *
     * @return $this
     */
    public function setLimitBasis($limit_basis)
    {
        $allowedValues = $this->getLimitBasisAllowableValues();
        if (!is_null($limit_basis) && !in_array($limit_basis, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'limit_basis', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['limit_basis'] = $limit_basis;

        return $this;
    }

    /**
     * Gets limit_basis_text
     *
     * @return string|null
     */
    public function getLimitBasisText()
    {
        return $this->container['limit_basis_text'];
    }

    /**
     * Sets limit_basis_text
     *
     * @param string|null $limit_basis_text Trading limit unit label. crypto: crypto quantity, fiat: fiat amount
     *
     * @return $this
     */
    public function setLimitBasisText($limit_basis_text)
    {
        $allowedValues = $this->getLimitBasisTextAllowableValues();
        if (!is_null($limit_basis_text) && !in_array($limit_basis_text, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'limit_basis_text', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['limit_basis_text'] = $limit_basis_text;

        return $this;
    }

    /**
     * Gets trade_methods
     *
     * @return \GateApi\Model\P2pAdsListTradeMethod[]|null
     */
    public function getTradeMethods()
    {
        return $this->container['trade_methods'];
    }

    /**
     * Sets trade_methods
     *
     * @param \GateApi\Model\P2pAdsListTradeMethod[]|null $trade_methods Supported payment methods list
     *
     * @return $this
     */
    public function setTradeMethods($trade_methods)
    {
        $this->container['trade_methods'] = $trade_methods;

        return $this;
    }

    /**
     * Gets nick_name
     *
     * @return string|null
     */
    public function getNickName()
    {
        return $this->container['nick_name'];
    }

    /**
     * Sets nick_name
     *
     * @param string|null $nick_name Advertiser Nickname
     *
     * @return $this
     */
    public function setNickName($nick_name)
    {
        $this->container['nick_name'] = $nick_name;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


