<?php
/**
 * SquareApi
 * PHP version 7
 *
 * @category Class
 * @package  GateApi
 * @author   Gate
 * @link     https://www.gate.com
 */

/**
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: https://openapi-generator.tech
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */

namespace GateApi\Api;

use GateApi\ApiException;
use GateApi\Configuration;
use GateApi\GateApiException;
use GateApi\HeaderSelector;
use GateApi\ObjectSerializer;
use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;

/**
 * SquareApi Class Doc Comment
 *
 * @category Class
 * @package  GateApi
 * @author   Gate
 * @link     https://www.gate.com
 */
class SquareApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $host_index (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $host_index = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $host_index;
    }

    /**
     * Set the host index
     *
     * @param  int Host index (required)
     */
    public function setHostIndex($host_index)
    {
        $this->hostIndex = $host_index;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation listSquareAiSearch
     *
     * AI MCP Dynamic Search
     *
     * Note: the input parameter is an associative array with the keys listed as the parameter name below
     *
     * @param  string $keyword Search keyword (currency name or content keyword, e.g., BTC, ETH) (optional)
     * @param  string $currency Filter by currency (exact currency code, e.g., BTC, ETH, SOL) (optional)
     * @param  int $time_range Time range: 0 &#x3D; unlimited (default), 1 &#x3D; last day, 2 &#x3D; last week, 3 &#x3D; last month (optional, default to 0)
     * @param  int $sort Sort order: 0 &#x3D; most popular (default), 1 &#x3D; latest (optional, default to 0)
     * @param  int $limit Return count, 1-50, default 10 (optional, default to 10)
     * @param  int $page Page number (optional, default to 1)
     *
     * @throws \GateApi\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \GateApi\Model\ListSquareAiSearchResponse|\GateApi\Model\ListSquareAiSearchError
     */
    public function listSquareAiSearch($associative_array)
    {
        list($response) = $this->listSquareAiSearchWithHttpInfo($associative_array);
        return $response;
    }

    /**
     * Operation listSquareAiSearchWithHttpInfo
     *
     * AI MCP Dynamic Search
     *
     * Note: the input parameter is an associative array with the keys listed as the parameter name below
     *
     * @param  string $keyword Search keyword (currency name or content keyword, e.g., BTC, ETH) (optional)
     * @param  string $currency Filter by currency (exact currency code, e.g., BTC, ETH, SOL) (optional)
     * @param  int $time_range Time range: 0 &#x3D; unlimited (default), 1 &#x3D; last day, 2 &#x3D; last week, 3 &#x3D; last month (optional, default to 0)
     * @param  int $sort Sort order: 0 &#x3D; most popular (default), 1 &#x3D; latest (optional, default to 0)
     * @param  int $limit Return count, 1-50, default 10 (optional, default to 10)
     * @param  int $page Page number (optional, default to 1)
     *
     * @throws \GateApi\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \GateApi\Model\ListSquareAiSearchResponse|\GateApi\Model\ListSquareAiSearchError, HTTP status code, HTTP response headers (array of strings)
     */
    public function listSquareAiSearchWithHttpInfo($associative_array)
    {
        $request = $this->listSquareAiSearchRequest($associative_array);

        $options = $this->createHttpClientOption();
        try {
            $response = $this->client->send($request, $options);
        } catch (RequestException $e) {
            $responseBody = $e->getResponse() ? (string) $e->getResponse()->getBody() : null;
            if ($responseBody != null) {
                $gateError = json_decode($responseBody, true);
                if ($gateError !== null && isset($gateError['label'])) {
                    throw new GateApiException(
                        $gateError,
                        $e->getCode(),
                        $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                        $responseBody
                    );
                }
            }
            throw new ApiException(
                "[{$e->getCode()}] {$e->getMessage()}",
                $e->getCode(),
                $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                $responseBody
            );
        }

        $returnType = '\GateApi\Model\ListSquareAiSearchResponse';
        $responseBody = $response->getBody();
        if ($returnType === '\SplFileObject') {
            $content = $responseBody; //stream goes to serializer
        } else {
            $content = (string) $responseBody;
        }

        return [
            ObjectSerializer::deserialize($content, $returnType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    /**
     * Operation listSquareAiSearchAsync
     *
     * AI MCP Dynamic Search
     *
     * Note: the input parameter is an associative array with the keys listed as the parameter name below
     *
     * @param  string $keyword Search keyword (currency name or content keyword, e.g., BTC, ETH) (optional)
     * @param  string $currency Filter by currency (exact currency code, e.g., BTC, ETH, SOL) (optional)
     * @param  int $time_range Time range: 0 &#x3D; unlimited (default), 1 &#x3D; last day, 2 &#x3D; last week, 3 &#x3D; last month (optional, default to 0)
     * @param  int $sort Sort order: 0 &#x3D; most popular (default), 1 &#x3D; latest (optional, default to 0)
     * @param  int $limit Return count, 1-50, default 10 (optional, default to 10)
     * @param  int $page Page number (optional, default to 1)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listSquareAiSearchAsync($associative_array)
    {
        return $this->listSquareAiSearchAsyncWithHttpInfo($associative_array)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation listSquareAiSearchAsyncWithHttpInfo
     *
     * AI MCP Dynamic Search
     *
     * Note: the input parameter is an associative array with the keys listed as the parameter name below
     *
     * @param  string $keyword Search keyword (currency name or content keyword, e.g., BTC, ETH) (optional)
     * @param  string $currency Filter by currency (exact currency code, e.g., BTC, ETH, SOL) (optional)
     * @param  int $time_range Time range: 0 &#x3D; unlimited (default), 1 &#x3D; last day, 2 &#x3D; last week, 3 &#x3D; last month (optional, default to 0)
     * @param  int $sort Sort order: 0 &#x3D; most popular (default), 1 &#x3D; latest (optional, default to 0)
     * @param  int $limit Return count, 1-50, default 10 (optional, default to 10)
     * @param  int $page Page number (optional, default to 1)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listSquareAiSearchAsyncWithHttpInfo($associative_array)
    {
        $returnType = '\GateApi\Model\ListSquareAiSearchResponse';
        $request = $this->listSquareAiSearchRequest($associative_array);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'listSquareAiSearch'
     *
     * Note: the input parameter is an associative array with the keys listed as the parameter name below
     *
     * @param  string $keyword Search keyword (currency name or content keyword, e.g., BTC, ETH) (optional)
     * @param  string $currency Filter by currency (exact currency code, e.g., BTC, ETH, SOL) (optional)
     * @param  int $time_range Time range: 0 &#x3D; unlimited (default), 1 &#x3D; last day, 2 &#x3D; last week, 3 &#x3D; last month (optional, default to 0)
     * @param  int $sort Sort order: 0 &#x3D; most popular (default), 1 &#x3D; latest (optional, default to 0)
     * @param  int $limit Return count, 1-50, default 10 (optional, default to 10)
     * @param  int $page Page number (optional, default to 1)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function listSquareAiSearchRequest($associative_array)
    {
        // unbox the parameters from the associative array
        $keyword = array_key_exists('keyword', $associative_array) ? $associative_array['keyword'] : null;
        $currency = array_key_exists('currency', $associative_array) ? $associative_array['currency'] : null;
        $time_range = array_key_exists('time_range', $associative_array) ? $associative_array['time_range'] : 0;
        $sort = array_key_exists('sort', $associative_array) ? $associative_array['sort'] : 0;
        $limit = array_key_exists('limit', $associative_array) ? $associative_array['limit'] : 10;
        $page = array_key_exists('page', $associative_array) ? $associative_array['page'] : 1;

        if ($limit !== null && $limit > 50) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling SquareApi.listSquareAiSearch, must be smaller than or equal to 50.');
        }
        if ($limit !== null && $limit < 1) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling SquareApi.listSquareAiSearch, must be bigger than or equal to 1.');
        }

        if ($page !== null && $page < 1) {
            throw new \InvalidArgumentException('invalid value for "$page" when calling SquareApi.listSquareAiSearch, must be bigger than or equal to 1.');
        }


        $resourcePath = '/social/message/search';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($keyword !== null) {
            if('form' === 'form' && is_array($keyword)) {
                foreach($keyword as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['keyword'] = $keyword;
            }
        }

        // query params
        if ($currency !== null) {
            if('form' === 'form' && is_array($currency)) {
                foreach($currency as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['currency'] = $currency;
            }
        }

        // query params
        if ($time_range !== null) {
            if('form' === 'form' && is_array($time_range)) {
                foreach($time_range as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['time_range'] = $time_range;
            }
        }

        // query params
        if ($sort !== null) {
            if('form' === 'form' && is_array($sort)) {
                foreach($sort as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['sort'] = $sort;
            }
        }

        // query params
        if ($limit !== null) {
            if('form' === 'form' && is_array($limit)) {
                foreach($limit as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['limit'] = $limit;
            }
        }

        // query params
        if ($page !== null) {
            if('form' === 'form' && is_array($page)) {
                foreach($page as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['page'] = $page;
            }
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($_tempBody));
            } else {
                $httpBody = $_tempBody;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        // Set default X-Gate-Size-Decimal header for futures API
        $defaultHeaders['X-Gate-Size-Decimal'] = '1';

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation listLiveReplay
     *
     * Gate AI Assistant live stream data retrieval
     *
     * Note: the input parameter is an associative array with the keys listed as the parameter name below
     *
     * @param  string $tag Business type filter. Available values: Market Analysis, Hot Topics, Blockchain, Others (optional)
     * @param  string $coin Filter by currency name (e.g., BTC, ETH) (optional)
     * @param  string $sort Sort order: hot &#x3D; most popular (default), new &#x3D; latest (optional, default to 'hot')
     * @param  int $limit Return count, 1-10, default 3 (optional, default to 3)
     *
     * @throws \GateApi\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \GateApi\Model\ListLiveReplayResponse|\GateApi\Model\ListLiveReplayError
     */
    public function listLiveReplay($associative_array)
    {
        list($response) = $this->listLiveReplayWithHttpInfo($associative_array);
        return $response;
    }

    /**
     * Operation listLiveReplayWithHttpInfo
     *
     * Gate AI Assistant live stream data retrieval
     *
     * Note: the input parameter is an associative array with the keys listed as the parameter name below
     *
     * @param  string $tag Business type filter. Available values: Market Analysis, Hot Topics, Blockchain, Others (optional)
     * @param  string $coin Filter by currency name (e.g., BTC, ETH) (optional)
     * @param  string $sort Sort order: hot &#x3D; most popular (default), new &#x3D; latest (optional, default to 'hot')
     * @param  int $limit Return count, 1-10, default 3 (optional, default to 3)
     *
     * @throws \GateApi\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \GateApi\Model\ListLiveReplayResponse|\GateApi\Model\ListLiveReplayError, HTTP status code, HTTP response headers (array of strings)
     */
    public function listLiveReplayWithHttpInfo($associative_array)
    {
        $request = $this->listLiveReplayRequest($associative_array);

        $options = $this->createHttpClientOption();
        try {
            $response = $this->client->send($request, $options);
        } catch (RequestException $e) {
            $responseBody = $e->getResponse() ? (string) $e->getResponse()->getBody() : null;
            if ($responseBody != null) {
                $gateError = json_decode($responseBody, true);
                if ($gateError !== null && isset($gateError['label'])) {
                    throw new GateApiException(
                        $gateError,
                        $e->getCode(),
                        $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                        $responseBody
                    );
                }
            }
            throw new ApiException(
                "[{$e->getCode()}] {$e->getMessage()}",
                $e->getCode(),
                $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                $responseBody
            );
        }

        $returnType = '\GateApi\Model\ListLiveReplayResponse';
        $responseBody = $response->getBody();
        if ($returnType === '\SplFileObject') {
            $content = $responseBody; //stream goes to serializer
        } else {
            $content = (string) $responseBody;
        }

        return [
            ObjectSerializer::deserialize($content, $returnType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    /**
     * Operation listLiveReplayAsync
     *
     * Gate AI Assistant live stream data retrieval
     *
     * Note: the input parameter is an associative array with the keys listed as the parameter name below
     *
     * @param  string $tag Business type filter. Available values: Market Analysis, Hot Topics, Blockchain, Others (optional)
     * @param  string $coin Filter by currency name (e.g., BTC, ETH) (optional)
     * @param  string $sort Sort order: hot &#x3D; most popular (default), new &#x3D; latest (optional, default to 'hot')
     * @param  int $limit Return count, 1-10, default 3 (optional, default to 3)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listLiveReplayAsync($associative_array)
    {
        return $this->listLiveReplayAsyncWithHttpInfo($associative_array)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation listLiveReplayAsyncWithHttpInfo
     *
     * Gate AI Assistant live stream data retrieval
     *
     * Note: the input parameter is an associative array with the keys listed as the parameter name below
     *
     * @param  string $tag Business type filter. Available values: Market Analysis, Hot Topics, Blockchain, Others (optional)
     * @param  string $coin Filter by currency name (e.g., BTC, ETH) (optional)
     * @param  string $sort Sort order: hot &#x3D; most popular (default), new &#x3D; latest (optional, default to 'hot')
     * @param  int $limit Return count, 1-10, default 3 (optional, default to 3)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listLiveReplayAsyncWithHttpInfo($associative_array)
    {
        $returnType = '\GateApi\Model\ListLiveReplayResponse';
        $request = $this->listLiveReplayRequest($associative_array);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'listLiveReplay'
     *
     * Note: the input parameter is an associative array with the keys listed as the parameter name below
     *
     * @param  string $tag Business type filter. Available values: Market Analysis, Hot Topics, Blockchain, Others (optional)
     * @param  string $coin Filter by currency name (e.g., BTC, ETH) (optional)
     * @param  string $sort Sort order: hot &#x3D; most popular (default), new &#x3D; latest (optional, default to 'hot')
     * @param  int $limit Return count, 1-10, default 3 (optional, default to 3)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function listLiveReplayRequest($associative_array)
    {
        // unbox the parameters from the associative array
        $tag = array_key_exists('tag', $associative_array) ? $associative_array['tag'] : null;
        $coin = array_key_exists('coin', $associative_array) ? $associative_array['coin'] : null;
        $sort = array_key_exists('sort', $associative_array) ? $associative_array['sort'] : 'hot';
        $limit = array_key_exists('limit', $associative_array) ? $associative_array['limit'] : 3;

        if ($limit !== null && $limit > 10) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling SquareApi.listLiveReplay, must be smaller than or equal to 10.');
        }
        if ($limit !== null && $limit < 1) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling SquareApi.listLiveReplay, must be bigger than or equal to 1.');
        }


        $resourcePath = '/social/live/tag_coin_live_replay';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($tag !== null) {
            if('form' === 'form' && is_array($tag)) {
                foreach($tag as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['tag'] = $tag;
            }
        }

        // query params
        if ($coin !== null) {
            if('form' === 'form' && is_array($coin)) {
                foreach($coin as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['coin'] = $coin;
            }
        }

        // query params
        if ($sort !== null) {
            if('form' === 'form' && is_array($sort)) {
                foreach($sort as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['sort'] = $sort;
            }
        }

        // query params
        if ($limit !== null) {
            if('form' === 'form' && is_array($limit)) {
                foreach($limit as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['limit'] = $limit;
            }
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($_tempBody));
            } else {
                $httpBody = $_tempBody;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        // Set default X-Gate-Size-Decimal header for futures API
        $defaultHeaders['X-Gate-Size-Decimal'] = '1';

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
